import { General } from '../../types'
import { g } from './helpers'

const DONG = '#8b3a3a'

export const DONG_GENERALS: General[] = [
  g({ id: 'd_dongzhuo', name: '董卓', faction: 'dong', troopType: 'cavalry', rarity: 'elite', color: DONG,
    command: 75, strategy: 55, politics: 50, martial: 78, achievement: 72, charisma: 30,
    hp: 950, atk: 75, def: 60, speed: 50, morale: 65, range: 50, vision: 85,
    personality: { aggressiveness: 80, caution: 30, discipline: 40, greed: 95, loyalty: 15 },
    skills: ['roar', 'inspire'] }),
  g({ id: 'd_lvbu', name: '吕布', faction: 'dong', troopType: 'cavalry', rarity: 'legend', color: DONG,
    command: 70, strategy: 42, politics: 22, martial: 100, achievement: 78, charisma: 50,
    hp: 1500, atk: 105, def: 75, speed: 78, morale: 82, range: 50, vision: 90,
    personality: { aggressiveness: 95, caution: 10, discipline: 40, greed: 85, loyalty: 15 },
    skills: ['duel', 'charge', 'roar'] }),
  g({ id: 'd_libu', name: '李傕', faction: 'dong', troopType: 'cavalry', rarity: 'normal', color: DONG,
    command: 62, strategy: 42, politics: 35, martial: 72, achievement: 45, charisma: 25,
    hp: 880, atk: 70, def: 52, speed: 60, morale: 60, range: 50, vision: 80,
    personality: { aggressiveness: 85, caution: 15, discipline: 30, greed: 90, loyalty: 20 },
    skills: ['charge'] }),
  g({ id: 'd_guosi', name: '郭汜', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 58, strategy: 38, politics: 30, martial: 70, achievement: 40, charisma: 22,
    hp: 860, atk: 68, def: 55, speed: 52, morale: 58, range: 50, vision: 78,
    personality: { aggressiveness: 82, caution: 18, discipline: 28, greed: 88, loyalty: 18 },
    skills: ['roar'] }),
  g({ id: 'd_huaxiong', name: '华雄', faction: 'dong', troopType: 'cavalry', rarity: 'elite', color: DONG,
    command: 60, strategy: 35, politics: 22, martial: 85, achievement: 42, charisma: 38,
    hp: 980, atk: 82, def: 55, speed: 60, morale: 68, range: 50, vision: 75,
    personality: { aggressiveness: 92, caution: 8, discipline: 40, greed: 65, loyalty: 55 },
    skills: ['duel'] }),
  g({ id: 'd_niufu', name: '牛辅', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 52, strategy: 30, politics: 25, martial: 65, achievement: 32, charisma: 20,
    hp: 820, atk: 62, def: 50, speed: 48, morale: 55, range: 50, vision: 75,
    personality: { aggressiveness: 70, caution: 25, discipline: 35, greed: 75, loyalty: 30 },
    skills: ['fortify'] }),
  g({ id: 'd_zhangji', name: '张济', faction: 'dong', troopType: 'spearman', rarity: 'normal', color: DONG,
    command: 58, strategy: 40, politics: 35, martial: 68, achievement: 38, charisma: 35,
    hp: 860, atk: 65, def: 55, speed: 50, morale: 62, range: 50, vision: 80,
    personality: { aggressiveness: 60, caution: 40, discipline: 50, greed: 60, loyalty: 40 },
    skills: ['fortify'] }),
  g({ id: 'd_gaoshun', name: '高顺', faction: 'dong', troopType: 'spearman', rarity: 'elite', color: DONG,
    command: 82, strategy: 58, politics: 42, martial: 82, achievement: 60, charisma: 65,
    hp: 980, atk: 78, def: 72, speed: 48, morale: 88, range: 50, vision: 88,
    personality: { aggressiveness: 65, caution: 45, discipline: 95, greed: 10, loyalty: 95 },
    skills: ['fortify', 'charge'] }),
  g({ id: 'd_chenggong', name: '陈宫', faction: 'dong', troopType: 'archer', rarity: 'elite', color: DONG,
    command: 70, strategy: 90, politics: 72, martial: 35, achievement: 60, charisma: 72,
    hp: 650, atk: 42, def: 45, speed: 48, morale: 80, range: 140, vision: 125,
    personality: { aggressiveness: 45, caution: 70, discipline: 78, greed: 20, loyalty: 90 },
    skills: ['stratagem', 'fire_attack'] }),
  g({ id: 'd_lijue2', name: '李儒', faction: 'dong', troopType: 'archer', rarity: 'elite', color: DONG,
    command: 55, strategy: 85, politics: 70, martial: 28, achievement: 48, charisma: 30,
    hp: 580, atk: 38, def: 35, speed: 45, morale: 65, range: 140, vision: 120,
    personality: { aggressiveness: 40, caution: 80, discipline: 70, greed: 50, loyalty: 60 },
    skills: ['fire_attack', 'stratagem'] }),
  // 补充
  g({ id: 'd_fandchou', name: '樊稠', faction: 'dong', troopType: 'cavalry', rarity: 'normal', color: DONG,
    command: 55, strategy: 35, politics: 28, martial: 68, achievement: 32, charisma: 30,
    hp: 840, atk: 65, def: 50, speed: 58, morale: 58, range: 50, vision: 78,
    personality: { aggressiveness: 75, caution: 20, discipline: 35, greed: 70, loyalty: 25 },
    skills: ['charge'] }),
  g({ id: 'd_diaochan', name: '貂蝉', faction: 'dong', troopType: 'infantry', rarity: 'elite', color: DONG,
    command: 30, strategy: 80, politics: 72, martial: 18, achievement: 55, charisma: 95,
    hp: 420, atk: 20, def: 25, speed: 45, morale: 90, range: 50, vision: 100,
    personality: { aggressiveness: 10, caution: 90, discipline: 80, greed: 10, loyalty: 50 },
    skills: ['inspire', 'rally'] }),
  g({ id: 'd_houchen', name: '侯成', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 48, strategy: 32, politics: 25, martial: 62, achievement: 28, charisma: 28,
    hp: 800, atk: 58, def: 48, speed: 48, morale: 50, range: 50, vision: 72,
    personality: { aggressiveness: 55, caution: 45, discipline: 38, greed: 60, loyalty: 20 },
    skills: ['fortify'] }),
  g({ id: 'd_songjian', name: '宋宪', faction: 'dong', troopType: 'spearman', rarity: 'normal', color: DONG,
    command: 45, strategy: 28, politics: 22, martial: 60, achievement: 25, charisma: 25,
    hp: 790, atk: 56, def: 48, speed: 46, morale: 48, range: 50, vision: 70,
    personality: { aggressiveness: 52, caution: 48, discipline: 35, greed: 58, loyalty: 18 },
    skills: ['fortify'] }),
  g({ id: 'd_weixu', name: '魏续', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 42, strategy: 25, politics: 20, martial: 58, achievement: 22, charisma: 22,
    hp: 780, atk: 55, def: 45, speed: 45, morale: 46, range: 50, vision: 68,
    personality: { aggressiveness: 50, caution: 50, discipline: 32, greed: 55, loyalty: 15 },
    skills: ['ambush'] }),
  g({ id: 'd_caodeng', name: '曹性', faction: 'dong', troopType: 'archer', rarity: 'normal', color: DONG,
    command: 42, strategy: 35, politics: 22, martial: 65, achievement: 25, charisma: 28,
    hp: 760, atk: 62, def: 40, speed: 48, morale: 55, range: 150, vision: 90,
    personality: { aggressiveness: 55, caution: 40, discipline: 42, greed: 40, loyalty: 50 },
    skills: ['snipe'] }),
  g({ id: 'd_zhangxiu2', name: '张绣', faction: 'dong', troopType: 'cavalry', rarity: 'normal', color: DONG,
    command: 70, strategy: 58, politics: 42, martial: 80, achievement: 55, charisma: 50,
    hp: 900, atk: 75, def: 55, speed: 62, morale: 70, range: 50, vision: 88,
    personality: { aggressiveness: 72, caution: 40, discipline: 55, greed: 60, loyalty: 45 },
    skills: ['ambush', 'charge'] }),
  g({ id: 'd_yanliangd', name: '严氏', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 35, strategy: 48, politics: 55, martial: 18, achievement: 20, charisma: 62,
    hp: 450, atk: 22, def: 30, speed: 38, morale: 68, range: 50, vision: 85,
    personality: { aggressiveness: 8, caution: 90, discipline: 72, greed: 8, loyalty: 88 },
    skills: ['heal'] }),
  g({ id: 'd_lilingqi', name: '吕玲绮', faction: 'dong', troopType: 'cavalry', rarity: 'elite', color: DONG,
    command: 55, strategy: 45, politics: 30, martial: 82, achievement: 35, charisma: 65,
    hp: 880, atk: 78, def: 50, speed: 70, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 78, caution: 25, discipline: 55, greed: 15, loyalty: 88 },
    skills: ['charge', 'duel'] }),
  g({ id: 'd_zangba', name: '臧霸', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 65, strategy: 50, politics: 42, martial: 72, achievement: 48, charisma: 55,
    hp: 880, atk: 68, def: 58, speed: 50, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 62, caution: 38, discipline: 58, greed: 35, loyalty: 55 },
    skills: ['fortify', 'charge'] }),
]
