import { General } from '../../types'
import { g } from './helpers'

const JIN = '#8a8abf'

export const JIN_GENERALS: General[] = [
  g({ id: 'j_simayan', name: '司马炎', faction: 'jin', troopType: 'cavalry', rarity: 'elite', color: JIN,
    command: 78, strategy: 72, politics: 82, martial: 55, achievement: 85, charisma: 70,
    hp: 820, atk: 58, def: 60, speed: 52, morale: 82, range: 50, vision: 100,
    personality: { aggressiveness: 50, caution: 60, discipline: 75, greed: 55, loyalty: 70 },
    skills: ['inspire', 'rally'] }),
  g({ id: 'j_simazhao', name: '司马昭', faction: 'jin', troopType: 'infantry', rarity: 'elite', color: JIN,
    command: 82, strategy: 85, politics: 82, martial: 55, achievement: 80, charisma: 55,
    hp: 780, atk: 55, def: 58, speed: 48, morale: 78, range: 50, vision: 110,
    personality: { aggressiveness: 55, caution: 70, discipline: 80, greed: 85, loyalty: 50 },
    skills: ['stratagem', 'ambush'] }),
  g({ id: 'j_simashi', name: '司马师', faction: 'jin', troopType: 'infantry', rarity: 'elite', color: JIN,
    command: 80, strategy: 78, politics: 80, martial: 58, achievement: 72, charisma: 60,
    hp: 800, atk: 58, def: 60, speed: 48, morale: 80, range: 50, vision: 105,
    personality: { aggressiveness: 45, caution: 72, discipline: 85, greed: 70, loyalty: 55 },
    skills: ['fortify', 'stratagem'] }),
  g({ id: 'j_dengai2', name: '邓艾', faction: 'jin', troopType: 'infantry', rarity: 'legend', color: JIN,
    command: 88, strategy: 85, politics: 60, martial: 78, achievement: 80, charisma: 55,
    hp: 880, atk: 72, def: 65, speed: 55, morale: 82, range: 50, vision: 110,
    personality: { aggressiveness: 70, caution: 55, discipline: 85, greed: 65, loyalty: 75 },
    skills: ['ambush', 'stratagem'] }),
  g({ id: 'j_zhonghui2', name: '钟会', faction: 'jin', troopType: 'cavalry', rarity: 'elite', color: JIN,
    command: 82, strategy: 88, politics: 75, martial: 55, achievement: 72, charisma: 48,
    hp: 750, atk: 55, def: 55, speed: 55, morale: 70, range: 50, vision: 115,
    personality: { aggressiveness: 60, caution: 55, discipline: 65, greed: 85, loyalty: 25 },
    skills: ['stratagem', 'fire_attack'] }),
  g({ id: 'j_duyu', name: '杜预', faction: 'jin', troopType: 'archer', rarity: 'elite', color: JIN,
    command: 85, strategy: 88, politics: 82, martial: 50, achievement: 78, charisma: 72,
    hp: 720, atk: 52, def: 50, speed: 48, morale: 82, range: 150, vision: 120,
    personality: { aggressiveness: 45, caution: 68, discipline: 88, greed: 20, loyalty: 85 },
    skills: ['stratagem', 'snipe'] }),
  g({ id: 'j_wangjun', name: '王濬', faction: 'jin', troopType: 'infantry', rarity: 'elite', color: JIN,
    command: 78, strategy: 72, politics: 65, martial: 72, achievement: 72, charisma: 65,
    hp: 880, atk: 68, def: 62, speed: 52, morale: 80, range: 50, vision: 95,
    personality: { aggressiveness: 62, caution: 50, discipline: 78, greed: 35, loyalty: 80 },
    skills: ['charge', 'fortify'] }),
  g({ id: 'j_yanghu', name: '羊祜', faction: 'jin', troopType: 'shield', rarity: 'elite', color: JIN,
    command: 82, strategy: 80, politics: 88, martial: 48, achievement: 75, charisma: 90,
    hp: 750, atk: 45, def: 65, speed: 42, morale: 88, range: 50, vision: 105,
    personality: { aggressiveness: 25, caution: 80, discipline: 92, greed: 8, loyalty: 92 },
    skills: ['rally', 'heal'] }),
  g({ id: 'j_jiachong', name: '贾充', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 55, strategy: 68, politics: 72, martial: 35, achievement: 55, charisma: 30,
    hp: 650, atk: 40, def: 45, speed: 42, morale: 65, range: 50, vision: 90,
    personality: { aggressiveness: 40, caution: 72, discipline: 60, greed: 85, loyalty: 35 },
    skills: ['stratagem'] }),
  g({ id: 'j_wenjyang', name: '文鸯', faction: 'jin', troopType: 'cavalry', rarity: 'elite', color: JIN,
    command: 65, strategy: 48, politics: 30, martial: 92, achievement: 55, charisma: 60,
    hp: 1000, atk: 88, def: 58, speed: 72, morale: 78, range: 50, vision: 82,
    personality: { aggressiveness: 88, caution: 15, discipline: 62, greed: 30, loyalty: 65 },
    skills: ['charge', 'duel'] }),
  // 补充
  g({ id: 'j_zhugexu', name: '诸葛绪', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 58, strategy: 52, politics: 48, martial: 55, achievement: 40, charisma: 42,
    hp: 780, atk: 52, def: 55, speed: 45, morale: 65, range: 50, vision: 85,
    personality: { aggressiveness: 40, caution: 62, discipline: 65, greed: 45, loyalty: 55 },
    skills: ['fortify'] }),
  g({ id: 'j_wangyuan', name: '王元姬', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 38, strategy: 62, politics: 72, martial: 18, achievement: 35, charisma: 75,
    hp: 480, atk: 22, def: 32, speed: 40, morale: 78, range: 50, vision: 95,
    personality: { aggressiveness: 8, caution: 92, discipline: 88, greed: 5, loyalty: 95 },
    skills: ['heal', 'rally'] }),
  g({ id: 'j_huzhao', name: '胡昭', faction: 'jin', troopType: 'archer', rarity: 'normal', color: JIN,
    command: 45, strategy: 72, politics: 68, martial: 25, achievement: 35, charisma: 62,
    hp: 580, atk: 35, def: 38, speed: 42, morale: 72, range: 140, vision: 100,
    personality: { aggressiveness: 15, caution: 82, discipline: 78, greed: 8, loyalty: 85 },
    skills: ['stratagem'] }),
  g({ id: 'j_zhongyu', name: '钟毓', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 55, strategy: 62, politics: 65, martial: 42, achievement: 38, charisma: 50,
    hp: 720, atk: 45, def: 50, speed: 45, morale: 68, range: 50, vision: 88,
    personality: { aggressiveness: 35, caution: 65, discipline: 72, greed: 40, loyalty: 58 },
    skills: ['stratagem'] }),
  g({ id: 'j_malong', name: '马隆', faction: 'jin', troopType: 'spearman', rarity: 'elite', color: JIN,
    command: 75, strategy: 68, politics: 55, martial: 78, achievement: 58, charisma: 62,
    hp: 920, atk: 72, def: 68, speed: 52, morale: 80, range: 50, vision: 90,
    personality: { aggressiveness: 58, caution: 50, discipline: 82, greed: 22, loyalty: 82 },
    skills: ['fortify', 'charge'] }),
  g({ id: 'j_tangbin', name: '唐彬', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 62, strategy: 55, politics: 52, martial: 62, achievement: 42, charisma: 50,
    hp: 830, atk: 58, def: 58, speed: 48, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 48, caution: 55, discipline: 72, greed: 25, loyalty: 75 },
    skills: ['fortify'] }),
  g({ id: 'j_huwei', name: '胡奋', faction: 'jin', troopType: 'cavalry', rarity: 'normal', color: JIN,
    command: 60, strategy: 50, politics: 48, martial: 68, achievement: 42, charisma: 48,
    hp: 860, atk: 65, def: 52, speed: 58, morale: 70, range: 50, vision: 80,
    personality: { aggressiveness: 58, caution: 42, discipline: 65, greed: 30, loyalty: 72 },
    skills: ['charge'] }),
  g({ id: 'j_zhanghua', name: '张华', faction: 'jin', troopType: 'archer', rarity: 'elite', color: JIN,
    command: 58, strategy: 78, politics: 82, martial: 25, achievement: 55, charisma: 68,
    hp: 580, atk: 35, def: 38, speed: 42, morale: 75, range: 140, vision: 108,
    personality: { aggressiveness: 18, caution: 78, discipline: 82, greed: 15, loyalty: 80 },
    skills: ['stratagem', 'heal'] }),
  g({ id: 'j_wangrong', name: '王戎', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 55, strategy: 65, politics: 62, martial: 42, achievement: 45, charisma: 48,
    hp: 700, atk: 45, def: 48, speed: 45, morale: 65, range: 50, vision: 88,
    personality: { aggressiveness: 30, caution: 68, discipline: 58, greed: 70, loyalty: 50 },
    skills: ['stratagem'] }),
  g({ id: 'j_simaliang', name: '司马亮', faction: 'jin', troopType: 'cavalry', rarity: 'normal', color: JIN,
    command: 55, strategy: 52, politics: 58, martial: 50, achievement: 42, charisma: 48,
    hp: 760, atk: 50, def: 50, speed: 52, morale: 62, range: 50, vision: 82,
    personality: { aggressiveness: 38, caution: 62, discipline: 55, greed: 52, loyalty: 55 },
    skills: ['inspire'] }),
]
