import { General } from '../../types'
import { g } from './helpers'

const JINGZHOU = '#5a8a6a'

export const JINGZHOU_GENERALS: General[] = [
  g({ id: 'jz_liubiao', name: '刘表', faction: 'jingzhou', troopType: 'infantry', rarity: 'elite', color: JINGZHOU,
    command: 60, strategy: 62, politics: 78, martial: 35, achievement: 58, charisma: 68,
    hp: 720, atk: 42, def: 50, speed: 40, morale: 75, range: 50, vision: 95,
    personality: { aggressiveness: 20, caution: 85, discipline: 72, greed: 35, loyalty: 55 },
    skills: ['rally'] }),
  g({ id: 'jz_huangzu', name: '黄祖', faction: 'jingzhou', troopType: 'archer', rarity: 'normal', color: JINGZHOU,
    command: 55, strategy: 48, politics: 50, martial: 58, achievement: 40, charisma: 38,
    hp: 750, atk: 55, def: 48, speed: 42, morale: 62, range: 140, vision: 90,
    personality: { aggressiveness: 50, caution: 60, discipline: 55, greed: 55, loyalty: 60 },
    skills: ['snipe'] }),
  g({ id: 'jz_caimao', name: '蔡瑁', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 58, strategy: 55, politics: 62, martial: 45, achievement: 42, charisma: 35,
    hp: 720, atk: 48, def: 52, speed: 42, morale: 60, range: 50, vision: 85,
    personality: { aggressiveness: 35, caution: 70, discipline: 55, greed: 80, loyalty: 25 },
    skills: ['fortify'] }),
  g({ id: 'jz_kuaiyue', name: '蒯越', faction: 'jingzhou', troopType: 'archer', rarity: 'elite', color: JINGZHOU,
    command: 62, strategy: 82, politics: 78, martial: 32, achievement: 48, charisma: 55,
    hp: 620, atk: 40, def: 42, speed: 45, morale: 72, range: 140, vision: 110,
    personality: { aggressiveness: 30, caution: 80, discipline: 75, greed: 50, loyalty: 45 },
    skills: ['stratagem', 'heal'] }),
  g({ id: 'jz_wentai', name: '文聘', faction: 'jingzhou', troopType: 'shield', rarity: 'elite', color: JINGZHOU,
    command: 75, strategy: 62, politics: 55, martial: 78, achievement: 58, charisma: 70,
    hp: 950, atk: 70, def: 75, speed: 45, morale: 85, range: 50, vision: 88,
    personality: { aggressiveness: 50, caution: 60, discipline: 88, greed: 15, loyalty: 90 },
    skills: ['shield_wall', 'fortify'] }),
  g({ id: 'jz_huangzhong2', name: '黄忠', faction: 'jingzhou', troopType: 'archer', rarity: 'elite', color: JINGZHOU,
    command: 72, strategy: 55, politics: 40, martial: 88, achievement: 68, charisma: 60,
    hp: 850, atk: 82, def: 55, speed: 45, morale: 85, range: 180, vision: 120,
    personality: { aggressiveness: 65, caution: 45, discipline: 80, greed: 40, loyalty: 90 },
    skills: ['snipe'] }),
  g({ id: 'jz_weiyan2', name: '魏延', faction: 'jingzhou', troopType: 'infantry', rarity: 'elite', color: JINGZHOU,
    command: 80, strategy: 68, politics: 38, martial: 88, achievement: 70, charisma: 45,
    hp: 980, atk: 82, def: 62, speed: 55, morale: 72, range: 50, vision: 90,
    personality: { aggressiveness: 85, caution: 25, discipline: 45, greed: 80, loyalty: 35 },
    skills: ['ambush', 'charge'] }),
  g({ id: 'jz_ganfu', name: '甘夫人', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 40, strategy: 55, politics: 65, martial: 20, achievement: 30, charisma: 78,
    hp: 500, atk: 25, def: 35, speed: 40, morale: 80, range: 50, vision: 90,
    personality: { aggressiveness: 10, caution: 90, discipline: 85, greed: 5, loyalty: 100 },
    skills: ['heal', 'rally'] }),
  // 补充
  g({ id: 'jz_liuqi', name: '刘琦', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 45, strategy: 42, politics: 50, martial: 35, achievement: 32, charisma: 48,
    hp: 650, atk: 38, def: 42, speed: 40, morale: 62, range: 50, vision: 82,
    personality: { aggressiveness: 25, caution: 72, discipline: 55, greed: 25, loyalty: 70 },
    skills: ['rally'] }),
  g({ id: 'jz_liucong', name: '刘琮', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 35, strategy: 38, politics: 42, martial: 25, achievement: 28, charisma: 35,
    hp: 580, atk: 30, def: 38, speed: 38, morale: 50, range: 50, vision: 78,
    personality: { aggressiveness: 12, caution: 88, discipline: 42, greed: 40, loyalty: 30 },
    skills: ['fortify'] }),
  g({ id: 'jz_yiji', name: '伊籍', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 42, strategy: 65, politics: 72, martial: 22, achievement: 35, charisma: 62,
    hp: 560, atk: 28, def: 35, speed: 42, morale: 70, range: 50, vision: 95,
    personality: { aggressiveness: 18, caution: 78, discipline: 72, greed: 12, loyalty: 82 },
    skills: ['heal', 'inspire'] }),
  g({ id: 'jz_huangsha', name: '霍峻', faction: 'jingzhou', troopType: 'shield', rarity: 'elite', color: JINGZHOU,
    command: 72, strategy: 58, politics: 50, martial: 72, achievement: 48, charisma: 62,
    hp: 920, atk: 65, def: 72, speed: 42, morale: 82, range: 50, vision: 85,
    personality: { aggressiveness: 42, caution: 65, discipline: 85, greed: 10, loyalty: 92 },
    skills: ['fortify', 'shield_wall'] }),
  g({ id: 'jz_xingdaorong', name: '邢道荣', faction: 'jingzhou', troopType: 'spearman', rarity: 'normal', color: JINGZHOU,
    command: 42, strategy: 25, politics: 18, martial: 70, achievement: 20, charisma: 30,
    hp: 860, atk: 68, def: 52, speed: 48, morale: 55, range: 50, vision: 72,
    personality: { aggressiveness: 78, caution: 15, discipline: 35, greed: 50, loyalty: 45 },
    skills: ['charge'] }),
  g({ id: 'jz_wangwei', name: '王威', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 58, strategy: 52, politics: 48, martial: 62, achievement: 35, charisma: 55,
    hp: 820, atk: 58, def: 55, speed: 45, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 55, caution: 52, discipline: 70, greed: 18, loyalty: 85 },
    skills: ['fortify'] }),
  g({ id: 'jz_dengyi', name: '邓义', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 48, strategy: 52, politics: 58, martial: 35, achievement: 28, charisma: 42,
    hp: 650, atk: 38, def: 42, speed: 42, morale: 62, range: 50, vision: 85,
    personality: { aggressiveness: 25, caution: 72, discipline: 62, greed: 35, loyalty: 55 },
    skills: ['heal'] }),
  g({ id: 'jz_liupan', name: '刘磐', faction: 'jingzhou', troopType: 'cavalry', rarity: 'normal', color: JINGZHOU,
    command: 55, strategy: 42, politics: 38, martial: 68, achievement: 35, charisma: 45,
    hp: 850, atk: 65, def: 52, speed: 58, morale: 68, range: 50, vision: 80,
    personality: { aggressiveness: 65, caution: 35, discipline: 55, greed: 35, loyalty: 65 },
    skills: ['charge'] }),
  g({ id: 'jz_zhangyan', name: '张允', faction: 'jingzhou', troopType: 'archer', rarity: 'normal', color: JINGZHOU,
    command: 52, strategy: 48, politics: 52, martial: 42, achievement: 30, charisma: 35,
    hp: 700, atk: 48, def: 42, speed: 45, morale: 55, range: 140, vision: 88,
    personality: { aggressiveness: 35, caution: 62, discipline: 48, greed: 60, loyalty: 32 },
    skills: ['snipe'] }),
  g({ id: 'jz_fuquan', name: '傅巽', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 38, strategy: 62, politics: 68, martial: 20, achievement: 28, charisma: 50,
    hp: 540, atk: 25, def: 32, speed: 40, morale: 62, range: 50, vision: 90,
    personality: { aggressiveness: 15, caution: 82, discipline: 65, greed: 48, loyalty: 35 },
    skills: ['stratagem'] }),
  g({ id: 'jz_huojun', name: '霍笃', faction: 'jingzhou', troopType: 'spearman', rarity: 'normal', color: JINGZHOU,
    command: 55, strategy: 42, politics: 38, martial: 65, achievement: 32, charisma: 48,
    hp: 850, atk: 62, def: 58, speed: 45, morale: 70, range: 50, vision: 78,
    personality: { aggressiveness: 50, caution: 48, discipline: 72, greed: 18, loyalty: 82 },
    skills: ['fortify'] }),
  g({ id: 'jz_hanxi', name: '韩嵩', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 42, strategy: 65, politics: 72, martial: 22, achievement: 35, charisma: 58,
    hp: 560, atk: 28, def: 35, speed: 42, morale: 68, range: 50, vision: 92,
    personality: { aggressiveness: 12, caution: 85, discipline: 75, greed: 12, loyalty: 78 },
    skills: ['heal', 'inspire'] }),
]
