import { General } from '../../types'
import { g } from './helpers'

const WEI = '#4a7cbf'

export const WEI_GENERALS: General[] = [
  g({
    id: 'caocao', name: '曹操', faction: 'wei', troopType: 'cavalry', rarity: 'legend', color: WEI,
    command: 96, strategy: 92, politics: 92, martial: 72, achievement: 98, charisma: 90,
    hp: 900, atk: 70, def: 65, speed: 55, morale: 95, range: 50, vision: 120,
    personality: { aggressiveness: 75, caution: 60, discipline: 85, greed: 60, loyalty: 70 },
    skills: ['stratagem', 'inspire'],
  }),
  g({
    id: 'simayi', name: '司马懿', faction: 'wei', troopType: 'infantry', rarity: 'legend', color: WEI,
    command: 90, strategy: 97, politics: 88, martial: 55, achievement: 90, charisma: 65,
    hp: 800, atk: 55, def: 70, speed: 45, morale: 80, range: 50, vision: 130,
    personality: { aggressiveness: 35, caution: 95, discipline: 90, greed: 80, loyalty: 40 },
    skills: ['fire_attack', 'fortify'],
  }),
  g({
    id: 'zhangliao', name: '张辽', faction: 'wei', troopType: 'cavalry', rarity: 'elite', color: WEI,
    command: 85, strategy: 72, politics: 55, martial: 88, achievement: 82, charisma: 78,
    hp: 950, atk: 82, def: 60, speed: 65, morale: 90, range: 50, vision: 100,
    personality: { aggressiveness: 80, caution: 45, discipline: 80, greed: 40, loyalty: 90 },
    skills: ['charge', 'roar'],
  }),
  g({
    id: 'xuhuang', name: '徐晃', faction: 'wei', troopType: 'infantry', rarity: 'elite', color: WEI,
    command: 82, strategy: 65, politics: 50, martial: 85, achievement: 75, charisma: 72,
    hp: 1000, atk: 78, def: 72, speed: 48, morale: 85, range: 50, vision: 90,
    personality: { aggressiveness: 60, caution: 55, discipline: 90, greed: 30, loyalty: 90 },
    skills: ['fortify', 'charge'],
  }),
  g({
    id: 'zhanghe', name: '张郃', faction: 'wei', troopType: 'spearman', rarity: 'elite', color: WEI,
    command: 80, strategy: 70, politics: 45, martial: 82, achievement: 72, charisma: 68,
    hp: 920, atk: 75, def: 68, speed: 55, morale: 82, range: 50, vision: 95,
    personality: { aggressiveness: 65, caution: 55, discipline: 75, greed: 45, loyalty: 70 },
    skills: ['ambush'],
  }),
  g({
    id: 'xiahoudun', name: '夏侯惇', faction: 'wei', troopType: 'cavalry', rarity: 'elite', color: WEI,
    command: 78, strategy: 55, politics: 48, martial: 90, achievement: 75, charisma: 80,
    hp: 1050, atk: 85, def: 65, speed: 58, morale: 92, range: 50, vision: 85,
    personality: { aggressiveness: 90, caution: 20, discipline: 75, greed: 50, loyalty: 95 },
    skills: ['charge', 'duel'],
  }),
  g({
    id: 'xiahouyuan', name: '夏侯渊', faction: 'wei', troopType: 'cavalry', rarity: 'elite', color: WEI,
    command: 80, strategy: 60, politics: 40, martial: 86, achievement: 70, charisma: 65,
    hp: 900, atk: 80, def: 55, speed: 70, morale: 80, range: 50, vision: 95,
    personality: { aggressiveness: 88, caution: 15, discipline: 60, greed: 55, loyalty: 85 },
    skills: ['ambush'],
  }),
  g({
    id: 'dengai', name: '邓艾', faction: 'wei', troopType: 'infantry', rarity: 'elite', color: WEI,
    command: 88, strategy: 85, politics: 60, martial: 78, achievement: 80, charisma: 55,
    hp: 880, atk: 72, def: 65, speed: 55, morale: 82, range: 50, vision: 110,
    personality: { aggressiveness: 70, caution: 55, discipline: 85, greed: 65, loyalty: 75 },
    skills: ['ambush', 'stratagem'],
  }),
  g({
    id: 'guojia', name: '郭嘉', faction: 'wei', troopType: 'archer', rarity: 'legend', color: WEI,
    command: 70, strategy: 98, politics: 80, martial: 35, achievement: 78, charisma: 82,
    hp: 650, atk: 50, def: 40, speed: 50, morale: 78, range: 150, vision: 140,
    personality: { aggressiveness: 55, caution: 70, discipline: 70, greed: 30, loyalty: 95 },
    skills: ['fire_attack', 'stratagem'],
  }),
  g({
    id: 'xunyu', name: '荀彧', faction: 'wei', troopType: 'infantry', rarity: 'elite', color: WEI,
    command: 72, strategy: 90, politics: 95, martial: 30, achievement: 80, charisma: 90,
    hp: 650, atk: 40, def: 45, speed: 42, morale: 85, range: 50, vision: 120,
    personality: { aggressiveness: 20, caution: 85, discipline: 95, greed: 10, loyalty: 98 },
    skills: ['rally', 'heal'],
  }),
  g({
    id: 'dianwei', name: '典韦', faction: 'wei', troopType: 'infantry', rarity: 'elite', color: WEI,
    command: 55, strategy: 30, politics: 20, martial: 95, achievement: 62, charisma: 55,
    hp: 1200, atk: 92, def: 70, speed: 50, morale: 88, range: 50, vision: 70,
    personality: { aggressiveness: 95, caution: 5, discipline: 65, greed: 15, loyalty: 100 },
    skills: ['duel', 'roar'],
  }),
  g({
    id: 'xuchu', name: '许褚', faction: 'wei', troopType: 'infantry', rarity: 'elite', color: WEI,
    command: 58, strategy: 28, politics: 18, martial: 94, achievement: 60, charisma: 50,
    hp: 1250, atk: 90, def: 75, speed: 45, morale: 85, range: 50, vision: 70,
    personality: { aggressiveness: 90, caution: 10, discipline: 70, greed: 20, loyalty: 100 },
    skills: ['shield_wall', 'duel'],
  }),
  g({
    id: 'caoren', name: '曹仁', faction: 'wei', troopType: 'shield', rarity: 'elite', color: WEI,
    command: 85, strategy: 65, politics: 55, martial: 80, achievement: 72, charisma: 70,
    hp: 1050, atk: 68, def: 80, speed: 45, morale: 90, range: 50, vision: 90,
    personality: { aggressiveness: 55, caution: 65, discipline: 90, greed: 20, loyalty: 92 },
    skills: ['fortify', 'shield_wall'],
  }),
  g({
    id: 'caohong', name: '曹洪', faction: 'wei', troopType: 'cavalry', rarity: 'normal', color: WEI,
    command: 72, strategy: 50, politics: 42, martial: 78, achievement: 58, charisma: 55,
    hp: 920, atk: 72, def: 58, speed: 60, morale: 80, range: 50, vision: 85,
    personality: { aggressiveness: 70, caution: 35, discipline: 65, greed: 55, loyalty: 85 },
    skills: ['charge'],
  }),
  g({
    id: 'yujin', name: '于禁', faction: 'wei', troopType: 'infantry', rarity: 'elite', color: WEI,
    command: 82, strategy: 62, politics: 55, martial: 72, achievement: 68, charisma: 60,
    hp: 950, atk: 68, def: 72, speed: 48, morale: 75, range: 50, vision: 90,
    personality: { aggressiveness: 50, caution: 65, discipline: 95, greed: 25, loyalty: 55 },
    skills: ['fortify'],
  }),
  g({
    id: 'yuejin', name: '乐进', faction: 'wei', troopType: 'infantry', rarity: 'normal', color: WEI,
    command: 72, strategy: 55, politics: 42, martial: 80, achievement: 60, charisma: 58,
    hp: 900, atk: 75, def: 60, speed: 58, morale: 82, range: 50, vision: 85,
    personality: { aggressiveness: 78, caution: 30, discipline: 75, greed: 35, loyalty: 88 },
    skills: ['charge'],
  }),
  g({
    id: 'lidian', name: '李典', faction: 'wei', troopType: 'archer', rarity: 'normal', color: WEI,
    command: 72, strategy: 68, politics: 55, martial: 72, achievement: 58, charisma: 65,
    hp: 850, atk: 65, def: 55, speed: 52, morale: 80, range: 140, vision: 100,
    personality: { aggressiveness: 45, caution: 65, discipline: 85, greed: 20, loyalty: 90 },
    skills: ['snipe'],
  }),
  g({
    id: 'pangde', name: '庞德', faction: 'wei', troopType: 'cavalry', rarity: 'elite', color: WEI,
    command: 70, strategy: 48, politics: 35, martial: 90, achievement: 60, charisma: 68,
    hp: 1000, atk: 85, def: 58, speed: 62, morale: 90, range: 50, vision: 80,
    personality: { aggressiveness: 88, caution: 12, discipline: 72, greed: 30, loyalty: 92 },
    skills: ['duel', 'charge'],
  }),
  g({
    id: 'zhonghui', name: '钟会', faction: 'wei', troopType: 'infantry', rarity: 'elite', color: WEI,
    command: 82, strategy: 88, politics: 75, martial: 55, achievement: 72, charisma: 48,
    hp: 750, atk: 55, def: 55, speed: 50, morale: 70, range: 50, vision: 115,
    personality: { aggressiveness: 60, caution: 55, discipline: 65, greed: 85, loyalty: 25 },
    skills: ['stratagem', 'fire_attack'],
  }),
  g({
    id: 'jiaxu', name: '贾诩', faction: 'wei', troopType: 'archer', rarity: 'legend', color: WEI,
    command: 68, strategy: 95, politics: 82, martial: 32, achievement: 72, charisma: 45,
    hp: 620, atk: 45, def: 42, speed: 48, morale: 72, range: 140, vision: 135,
    personality: { aggressiveness: 30, caution: 95, discipline: 80, greed: 50, loyalty: 35 },
    skills: ['fire_attack', 'ambush'],
  }),
]
