import { General } from '../../types'
import { g } from './helpers'

const XILIANG = '#bf8a3a'

export const XILIANG_GENERALS: General[] = [
  g({ id: 'xl_mateng', name: '马腾', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 78, strategy: 55, politics: 55, martial: 82, achievement: 62, charisma: 72,
    hp: 950, atk: 78, def: 58, speed: 62, morale: 80, range: 50, vision: 92,
    personality: { aggressiveness: 68, caution: 40, discipline: 65, greed: 40, loyalty: 82 },
    skills: ['charge', 'inspire'] }),
  g({ id: 'xl_hansui', name: '韩遂', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 72, strategy: 68, politics: 65, martial: 68, achievement: 58, charisma: 55,
    hp: 850, atk: 65, def: 55, speed: 58, morale: 68, range: 50, vision: 90,
    personality: { aggressiveness: 55, caution: 55, discipline: 50, greed: 70, loyalty: 30 },
    skills: ['stratagem', 'ambush'] }),
  g({ id: 'xl_machao2', name: '马超', faction: 'xiliang', troopType: 'cavalry', rarity: 'legend', color: XILIANG,
    command: 75, strategy: 50, politics: 35, martial: 95, achievement: 72, charisma: 65,
    hp: 1000, atk: 90, def: 58, speed: 72, morale: 78, range: 50, vision: 90,
    personality: { aggressiveness: 92, caution: 15, discipline: 50, greed: 70, loyalty: 55 },
    skills: ['charge', 'duel'] }),
  g({ id: 'xl_madai2', name: '马岱', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 68, strategy: 55, politics: 40, martial: 76, achievement: 52, charisma: 55,
    hp: 880, atk: 72, def: 55, speed: 65, morale: 76, range: 50, vision: 85,
    personality: { aggressiveness: 65, caution: 42, discipline: 68, greed: 35, loyalty: 82 },
    skills: ['ambush'] }),
  g({ id: 'xl_pangde2', name: '庞德', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 70, strategy: 48, politics: 35, martial: 90, achievement: 60, charisma: 68,
    hp: 1000, atk: 85, def: 58, speed: 62, morale: 90, range: 50, vision: 80,
    personality: { aggressiveness: 88, caution: 12, discipline: 72, greed: 30, loyalty: 92 },
    skills: ['duel', 'charge'] }),
  g({ id: 'xl_chengyi', name: '成宜', faction: 'xiliang', troopType: 'spearman', rarity: 'normal', color: XILIANG,
    command: 55, strategy: 38, politics: 30, martial: 68, achievement: 35, charisma: 42,
    hp: 850, atk: 65, def: 55, speed: 52, morale: 65, range: 50, vision: 78,
    personality: { aggressiveness: 72, caution: 28, discipline: 45, greed: 50, loyalty: 55 },
    skills: ['charge'] }),
  g({ id: 'xl_yanxing', name: '阎行', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 62, strategy: 45, politics: 32, martial: 85, achievement: 45, charisma: 48,
    hp: 920, atk: 80, def: 52, speed: 68, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 82, caution: 20, discipline: 55, greed: 45, loyalty: 60 },
    skills: ['duel'] }),
  g({ id: 'xl_liangxing', name: '梁兴', faction: 'xiliang', troopType: 'infantry', rarity: 'normal', color: XILIANG,
    command: 52, strategy: 35, politics: 28, martial: 65, achievement: 32, charisma: 38,
    hp: 820, atk: 62, def: 52, speed: 50, morale: 62, range: 50, vision: 76,
    personality: { aggressiveness: 68, caution: 30, discipline: 42, greed: 55, loyalty: 48 },
    skills: ['fortify'] }),
  // 补充
  g({ id: 'xl_matai', name: '马铁', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 50, strategy: 35, politics: 28, martial: 65, achievement: 28, charisma: 42,
    hp: 830, atk: 62, def: 48, speed: 62, morale: 68, range: 50, vision: 78,
    personality: { aggressiveness: 65, caution: 32, discipline: 55, greed: 30, loyalty: 85 },
    skills: ['charge'] }),
  g({ id: 'xl_mawan', name: '马玩', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 32, politics: 25, martial: 62, achievement: 25, charisma: 35,
    hp: 810, atk: 60, def: 45, speed: 60, morale: 60, range: 50, vision: 75,
    personality: { aggressiveness: 70, caution: 25, discipline: 40, greed: 50, loyalty: 45 },
    skills: ['charge'] }),
  g({ id: 'xl_houxuan', name: '侯选', faction: 'xiliang', troopType: 'spearman', rarity: 'normal', color: XILIANG,
    command: 50, strategy: 35, politics: 30, martial: 62, achievement: 28, charisma: 35,
    hp: 830, atk: 58, def: 55, speed: 48, morale: 60, range: 50, vision: 75,
    personality: { aggressiveness: 58, caution: 38, discipline: 48, greed: 48, loyalty: 42 },
    skills: ['fortify'] }),
  g({ id: 'xl_chengyin', name: '程银', faction: 'xiliang', troopType: 'infantry', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 32, politics: 25, martial: 60, achievement: 25, charisma: 32,
    hp: 800, atk: 58, def: 50, speed: 48, morale: 58, range: 50, vision: 72,
    personality: { aggressiveness: 62, caution: 32, discipline: 40, greed: 52, loyalty: 40 },
    skills: ['ambush'] }),
  g({ id: 'xl_yangqiu', name: '杨秋', faction: 'xiliang', troopType: 'archer', rarity: 'normal', color: XILIANG,
    command: 52, strategy: 42, politics: 35, martial: 58, achievement: 28, charisma: 38,
    hp: 760, atk: 55, def: 42, speed: 48, morale: 60, range: 140, vision: 88,
    personality: { aggressiveness: 50, caution: 48, discipline: 45, greed: 45, loyalty: 42 },
    skills: ['snipe'] }),
  g({ id: 'xl_zhangheng', name: '张横', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 30, politics: 22, martial: 64, achievement: 25, charisma: 30,
    hp: 820, atk: 62, def: 48, speed: 62, morale: 58, range: 50, vision: 75,
    personality: { aggressiveness: 72, caution: 22, discipline: 38, greed: 52, loyalty: 38 },
    skills: ['charge'] }),
  g({ id: 'xl_jiaxu', name: '贾诩', faction: 'xiliang', troopType: 'archer', rarity: 'legend', color: XILIANG,
    command: 68, strategy: 95, politics: 82, martial: 32, achievement: 72, charisma: 45,
    hp: 620, atk: 45, def: 42, speed: 48, morale: 72, range: 140, vision: 135,
    personality: { aggressiveness: 30, caution: 95, discipline: 80, greed: 50, loyalty: 35 },
    skills: ['fire_attack', 'ambush'] }),
  g({ id: 'xl_zhangxiu3', name: '张绣', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 70, strategy: 58, politics: 42, martial: 80, achievement: 55, charisma: 50,
    hp: 900, atk: 75, def: 55, speed: 62, morale: 70, range: 50, vision: 88,
    personality: { aggressiveness: 72, caution: 40, discipline: 55, greed: 60, loyalty: 45 },
    skills: ['ambush', 'charge'] }),
  g({ id: 'xl_liwei', name: '李堪', faction: 'xiliang', troopType: 'infantry', rarity: 'normal', color: XILIANG,
    command: 45, strategy: 30, politics: 25, martial: 60, achievement: 22, charisma: 30,
    hp: 800, atk: 58, def: 48, speed: 48, morale: 55, range: 50, vision: 72,
    personality: { aggressiveness: 65, caution: 30, discipline: 38, greed: 50, loyalty: 42 },
    skills: ['fortify'] }),
  g({ id: 'xl_machengji', name: '马承', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 35, politics: 28, martial: 62, achievement: 25, charisma: 40,
    hp: 820, atk: 60, def: 48, speed: 62, morale: 62, range: 50, vision: 75,
    personality: { aggressiveness: 60, caution: 35, discipline: 52, greed: 30, loyalty: 78 },
    skills: ['charge'] }),
  g({ id: 'xl_mazhong', name: '马忠', faction: 'xiliang', troopType: 'archer', rarity: 'normal', color: XILIANG,
    command: 50, strategy: 45, politics: 35, martial: 58, achievement: 30, charisma: 38,
    hp: 750, atk: 55, def: 42, speed: 48, morale: 60, range: 140, vision: 88,
    personality: { aggressiveness: 48, caution: 52, discipline: 50, greed: 38, loyalty: 55 },
    skills: ['snipe'] }),
  g({ id: 'xl_quanhui', name: '阙怀', faction: 'xiliang', troopType: 'shield', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 32, politics: 28, martial: 58, achievement: 22, charisma: 35,
    hp: 850, atk: 52, def: 62, speed: 42, morale: 60, range: 50, vision: 72,
    personality: { aggressiveness: 40, caution: 55, discipline: 52, greed: 35, loyalty: 50 },
    skills: ['shield_wall'] }),
]
