import { General } from '../../types'
import { g } from './helpers'

const YIZHOU = '#6a7a3a'

export const YIZHOU_GENERALS: General[] = [
  g({ id: 'yz_liuzhang', name: '刘璋', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 42, strategy: 45, politics: 58, martial: 28, achievement: 40, charisma: 52,
    hp: 650, atk: 35, def: 42, speed: 38, morale: 60, range: 50, vision: 85,
    personality: { aggressiveness: 15, caution: 90, discipline: 55, greed: 30, loyalty: 50 },
    skills: ['rally'] }),
  g({ id: 'yz_zhangren2', name: '张任', faction: 'yizhou', troopType: 'archer', rarity: 'elite', color: YIZHOU,
    command: 72, strategy: 65, politics: 48, martial: 78, achievement: 48, charisma: 62,
    hp: 860, atk: 72, def: 58, speed: 50, morale: 82, range: 150, vision: 100,
    personality: { aggressiveness: 58, caution: 55, discipline: 78, greed: 18, loyalty: 90 },
    skills: ['snipe', 'ambush'] }),
  g({ id: 'yz_yanyan2', name: '严颜', faction: 'yizhou', troopType: 'shield', rarity: 'elite', color: YIZHOU,
    command: 70, strategy: 52, politics: 48, martial: 75, achievement: 50, charisma: 68,
    hp: 950, atk: 65, def: 72, speed: 40, morale: 85, range: 50, vision: 80,
    personality: { aggressiveness: 45, caution: 60, discipline: 82, greed: 15, loyalty: 90 },
    skills: ['fortify', 'shield_wall'] }),
  g({ id: 'yz_wuyi', name: '吴懿', faction: 'yizhou', troopType: 'cavalry', rarity: 'normal', color: YIZHOU,
    command: 62, strategy: 48, politics: 52, martial: 65, achievement: 42, charisma: 55,
    hp: 850, atk: 62, def: 55, speed: 58, morale: 68, range: 50, vision: 82,
    personality: { aggressiveness: 50, caution: 55, discipline: 65, greed: 35, loyalty: 65 },
    skills: ['charge'] }),
  g({ id: 'yz_fazheng2', name: '法正', faction: 'yizhou', troopType: 'archer', rarity: 'elite', color: YIZHOU,
    command: 65, strategy: 92, politics: 78, martial: 40, achievement: 70, charisma: 55,
    hp: 680, atk: 48, def: 45, speed: 48, morale: 75, range: 140, vision: 125,
    personality: { aggressiveness: 55, caution: 65, discipline: 60, greed: 60, loyalty: 80 },
    skills: ['ambush', 'stratagem'] }),
  g({ id: 'yz_mengda', name: '孟达', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 55, strategy: 58, politics: 52, martial: 62, achievement: 38, charisma: 35,
    hp: 780, atk: 58, def: 50, speed: 50, morale: 55, range: 50, vision: 85,
    personality: { aggressiveness: 50, caution: 60, discipline: 40, greed: 70, loyalty: 20 },
    skills: ['ambush'] }),
  g({ id: 'yz_huangquan', name: '黄权', faction: 'yizhou', troopType: 'infantry', rarity: 'elite', color: YIZHOU,
    command: 72, strategy: 78, politics: 72, martial: 45, achievement: 52, charisma: 68,
    hp: 720, atk: 48, def: 55, speed: 45, morale: 78, range: 50, vision: 100,
    personality: { aggressiveness: 35, caution: 75, discipline: 82, greed: 15, loyalty: 85 },
    skills: ['stratagem', 'fortify'] }),
  g({ id: 'yz_leiton', name: '雷铜', faction: 'yizhou', troopType: 'spearman', rarity: 'normal', color: YIZHOU,
    command: 52, strategy: 38, politics: 30, martial: 68, achievement: 32, charisma: 40,
    hp: 850, atk: 65, def: 58, speed: 48, morale: 65, range: 50, vision: 78,
    personality: { aggressiveness: 62, caution: 40, discipline: 55, greed: 35, loyalty: 70 },
    skills: ['fortify'] }),
  // 补充
  g({ id: 'yz_zhanglu', name: '张鲁', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 55, strategy: 55, politics: 62, martial: 38, achievement: 45, charisma: 65,
    hp: 700, atk: 42, def: 48, speed: 42, morale: 72, range: 50, vision: 85,
    personality: { aggressiveness: 25, caution: 72, discipline: 60, greed: 35, loyalty: 55 },
    skills: ['rally', 'heal'] }),
  g({ id: 'yz_yanghuai', name: '杨怀', faction: 'yizhou', troopType: 'spearman', rarity: 'normal', color: YIZHOU,
    command: 52, strategy: 38, politics: 35, martial: 65, achievement: 30, charisma: 42,
    hp: 840, atk: 62, def: 55, speed: 48, morale: 65, range: 50, vision: 78,
    personality: { aggressiveness: 55, caution: 48, discipline: 58, greed: 40, loyalty: 65 },
    skills: ['fortify'] }),
  g({ id: 'yz_gaopei', name: '高沛', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 50, strategy: 35, politics: 30, martial: 62, achievement: 28, charisma: 38,
    hp: 820, atk: 60, def: 52, speed: 48, morale: 62, range: 50, vision: 75,
    personality: { aggressiveness: 58, caution: 42, discipline: 52, greed: 38, loyalty: 62 },
    skills: ['charge'] }),
  g({ id: 'yz_liuba', name: '刘巴', faction: 'yizhou', troopType: 'archer', rarity: 'elite', color: YIZHOU,
    command: 52, strategy: 78, politics: 82, martial: 22, achievement: 45, charisma: 55,
    hp: 550, atk: 32, def: 35, speed: 42, morale: 72, range: 130, vision: 105,
    personality: { aggressiveness: 15, caution: 85, discipline: 78, greed: 20, loyalty: 72 },
    skills: ['stratagem', 'heal'] }),
  g({ id: 'yz_wulan', name: '吴兰', faction: 'yizhou', troopType: 'cavalry', rarity: 'normal', color: YIZHOU,
    command: 48, strategy: 35, politics: 28, martial: 65, achievement: 28, charisma: 38,
    hp: 830, atk: 62, def: 48, speed: 58, morale: 60, range: 50, vision: 76,
    personality: { aggressiveness: 62, caution: 35, discipline: 48, greed: 40, loyalty: 60 },
    skills: ['charge'] }),
  g({ id: 'yz_pongxi', name: '庞羲', faction: 'yizhou', troopType: 'shield', rarity: 'normal', color: YIZHOU,
    command: 55, strategy: 42, politics: 50, martial: 55, achievement: 32, charisma: 45,
    hp: 850, atk: 52, def: 60, speed: 42, morale: 65, range: 50, vision: 80,
    personality: { aggressiveness: 38, caution: 62, discipline: 58, greed: 45, loyalty: 48 },
    skills: ['shield_wall'] }),
  g({ id: 'yz_liangyi', name: '秦宓', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 38, strategy: 72, politics: 75, martial: 18, achievement: 32, charisma: 65,
    hp: 500, atk: 25, def: 30, speed: 38, morale: 72, range: 50, vision: 95,
    personality: { aggressiveness: 10, caution: 88, discipline: 78, greed: 8, loyalty: 80 },
    skills: ['heal'] }),
  g({ id: 'yz_zhangyi', name: '张翼', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 62, strategy: 52, politics: 48, martial: 65, achievement: 42, charisma: 50,
    hp: 850, atk: 62, def: 58, speed: 48, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 48, caution: 55, discipline: 72, greed: 20, loyalty: 82 },
    skills: ['fortify'] }),
  g({ id: 'yz_liyan', name: '李严', faction: 'yizhou', troopType: 'shield', rarity: 'elite', color: YIZHOU,
    command: 72, strategy: 68, politics: 72, martial: 68, achievement: 55, charisma: 52,
    hp: 900, atk: 62, def: 68, speed: 45, morale: 72, range: 50, vision: 90,
    personality: { aggressiveness: 45, caution: 58, discipline: 65, greed: 65, loyalty: 50 },
    skills: ['fortify', 'shield_wall'] }),
  g({ id: 'yz_wanglian', name: '王连', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 42, strategy: 58, politics: 72, martial: 20, achievement: 32, charisma: 55,
    hp: 540, atk: 25, def: 35, speed: 40, morale: 68, range: 50, vision: 90,
    personality: { aggressiveness: 12, caution: 82, discipline: 78, greed: 15, loyalty: 78 },
    skills: ['heal'] }),
  g({ id: 'yz_deng', name: '邓芝', faction: 'yizhou', troopType: 'archer', rarity: 'normal', color: YIZHOU,
    command: 62, strategy: 68, politics: 72, martial: 48, achievement: 48, charisma: 62,
    hp: 720, atk: 48, def: 45, speed: 45, morale: 75, range: 140, vision: 98,
    personality: { aggressiveness: 35, caution: 62, discipline: 75, greed: 12, loyalty: 88 },
    skills: ['stratagem', 'snipe'] }),
  g({ id: 'yz_lengjin', name: '冷苞', faction: 'yizhou', troopType: 'cavalry', rarity: 'normal', color: YIZHOU,
    command: 50, strategy: 38, politics: 28, martial: 68, achievement: 28, charisma: 38,
    hp: 840, atk: 65, def: 48, speed: 58, morale: 62, range: 50, vision: 75,
    personality: { aggressiveness: 65, caution: 32, discipline: 48, greed: 42, loyalty: 58 },
    skills: ['charge'] }),
]
