import { General } from '../../types'
import { g } from './helpers'

const YUAN = '#7a6abf'

export const YUAN_GENERALS: General[] = [
  g({ id: 'y_yuanshao', name: '袁绍', faction: 'yuan', troopType: 'cavalry', rarity: 'elite', color: YUAN,
    command: 72, strategy: 60, politics: 70, martial: 55, achievement: 75, charisma: 72,
    hp: 850, atk: 55, def: 58, speed: 50, morale: 78, range: 50, vision: 100,
    personality: { aggressiveness: 55, caution: 60, discipline: 60, greed: 70, loyalty: 50 },
    skills: ['inspire', 'rally'] }),
  g({ id: 'y_yanliang', name: '颜良', faction: 'yuan', troopType: 'cavalry', rarity: 'elite', color: YUAN,
    command: 68, strategy: 38, politics: 25, martial: 92, achievement: 55, charisma: 48,
    hp: 1050, atk: 88, def: 58, speed: 65, morale: 75, range: 50, vision: 78,
    personality: { aggressiveness: 92, caution: 10, discipline: 55, greed: 50, loyalty: 72 },
    skills: ['charge', 'duel'] }),
  g({ id: 'y_wenchou', name: '文丑', faction: 'yuan', troopType: 'cavalry', rarity: 'elite', color: YUAN,
    command: 65, strategy: 35, politics: 22, martial: 90, achievement: 52, charisma: 45,
    hp: 1020, atk: 86, def: 55, speed: 62, morale: 72, range: 50, vision: 75,
    personality: { aggressiveness: 90, caution: 12, discipline: 50, greed: 55, loyalty: 70 },
    skills: ['duel', 'roar'] }),
  g({ id: 'y_tianfeng', name: '田丰', faction: 'yuan', troopType: 'infantry', rarity: 'elite', color: YUAN,
    command: 68, strategy: 88, politics: 80, martial: 30, achievement: 58, charisma: 70,
    hp: 640, atk: 40, def: 48, speed: 42, morale: 82, range: 50, vision: 120,
    personality: { aggressiveness: 30, caution: 90, discipline: 88, greed: 10, loyalty: 95 },
    skills: ['stratagem', 'heal'] }),
  g({ id: 'y_jushou', name: '沮授', faction: 'yuan', troopType: 'shield', rarity: 'elite', color: YUAN,
    command: 78, strategy: 85, politics: 78, martial: 38, achievement: 60, charisma: 75,
    hp: 700, atk: 42, def: 55, speed: 42, morale: 85, range: 50, vision: 115,
    personality: { aggressiveness: 30, caution: 82, discipline: 85, greed: 12, loyalty: 92 },
    skills: ['fortify', 'rally'] }),
  g({ id: 'y_guotu', name: '郭图', faction: 'yuan', troopType: 'archer', rarity: 'normal', color: YUAN,
    command: 48, strategy: 72, politics: 65, martial: 25, achievement: 35, charisma: 35,
    hp: 580, atk: 35, def: 38, speed: 42, morale: 60, range: 130, vision: 100,
    personality: { aggressiveness: 55, caution: 55, discipline: 40, greed: 75, loyalty: 40 },
    skills: ['stratagem'] }),
  g({ id: 'y_zhanghe2', name: '张郃', faction: 'yuan', troopType: 'spearman', rarity: 'elite', color: YUAN,
    command: 80, strategy: 70, politics: 45, martial: 82, achievement: 72, charisma: 68,
    hp: 920, atk: 75, def: 68, speed: 55, morale: 82, range: 50, vision: 95,
    personality: { aggressiveness: 65, caution: 55, discipline: 75, greed: 45, loyalty: 70 },
    skills: ['ambush'] }),
  g({ id: 'y_gaolan', name: '高览', faction: 'yuan', troopType: 'shield', rarity: 'normal', color: YUAN,
    command: 68, strategy: 52, politics: 40, martial: 76, achievement: 48, charisma: 55,
    hp: 920, atk: 70, def: 70, speed: 45, morale: 75, range: 50, vision: 85,
    personality: { aggressiveness: 55, caution: 50, discipline: 72, greed: 40, loyalty: 60 },
    skills: ['shield_wall'] }),
  g({ id: 'y_chunyuqiong', name: '淳于琼', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 55, strategy: 35, politics: 40, martial: 60, achievement: 35, charisma: 40,
    hp: 800, atk: 55, def: 50, speed: 42, morale: 55, range: 50, vision: 80,
    personality: { aggressiveness: 45, caution: 50, discipline: 30, greed: 60, loyalty: 50 },
    skills: ['fortify'] }),
  g({ id: 'y_yuantan', name: '袁谭', faction: 'yuan', troopType: 'cavalry', rarity: 'normal', color: YUAN,
    command: 55, strategy: 48, politics: 50, martial: 58, achievement: 40, charisma: 42,
    hp: 780, atk: 55, def: 48, speed: 55, morale: 62, range: 50, vision: 85,
    personality: { aggressiveness: 60, caution: 40, discipline: 45, greed: 70, loyalty: 35 },
    skills: ['charge'] }),
  // 补充
  g({ id: 'y_yuanxi', name: '袁熙', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 52, strategy: 45, politics: 48, martial: 52, achievement: 35, charisma: 40,
    hp: 740, atk: 50, def: 48, speed: 48, morale: 58, range: 50, vision: 82,
    personality: { aggressiveness: 42, caution: 55, discipline: 50, greed: 55, loyalty: 45 },
    skills: ['fortify'] }),
  g({ id: 'y_yuanshang', name: '袁尚', faction: 'yuan', troopType: 'cavalry', rarity: 'normal', color: YUAN,
    command: 50, strategy: 50, politics: 52, martial: 55, achievement: 38, charisma: 45,
    hp: 760, atk: 52, def: 48, speed: 55, morale: 60, range: 50, vision: 82,
    personality: { aggressiveness: 55, caution: 45, discipline: 42, greed: 72, loyalty: 32 },
    skills: ['charge'] }),
  g({ id: 'y_xupei', name: '许攸', faction: 'yuan', troopType: 'archer', rarity: 'elite', color: YUAN,
    command: 42, strategy: 82, politics: 68, martial: 22, achievement: 45, charisma: 28,
    hp: 520, atk: 30, def: 32, speed: 42, morale: 55, range: 130, vision: 115,
    personality: { aggressiveness: 45, caution: 55, discipline: 30, greed: 90, loyalty: 15 },
    skills: ['stratagem', 'ambush'] }),
  g({ id: 'y_fengji', name: '逢纪', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 45, strategy: 68, politics: 62, martial: 22, achievement: 32, charisma: 35,
    hp: 560, atk: 28, def: 35, speed: 40, morale: 60, range: 50, vision: 95,
    personality: { aggressiveness: 35, caution: 65, discipline: 55, greed: 60, loyalty: 50 },
    skills: ['stratagem'] }),
  g({ id: 'y_shenpei', name: '审配', faction: 'yuan', troopType: 'shield', rarity: 'elite', color: YUAN,
    command: 72, strategy: 68, politics: 70, martial: 45, achievement: 52, charisma: 68,
    hp: 780, atk: 48, def: 65, speed: 42, morale: 82, range: 50, vision: 95,
    personality: { aggressiveness: 40, caution: 68, discipline: 85, greed: 15, loyalty: 95 },
    skills: ['fortify', 'shield_wall'] }),
  g({ id: 'y_lvkuang', name: '吕旷', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 50, strategy: 38, politics: 32, martial: 62, achievement: 28, charisma: 35,
    hp: 800, atk: 58, def: 50, speed: 48, morale: 60, range: 50, vision: 75,
    personality: { aggressiveness: 55, caution: 42, discipline: 48, greed: 48, loyalty: 50 },
    skills: ['fortify'] }),
  g({ id: 'y_lvxiang', name: '吕翔', faction: 'yuan', troopType: 'cavalry', rarity: 'normal', color: YUAN,
    command: 48, strategy: 35, politics: 28, martial: 60, achievement: 25, charisma: 32,
    hp: 790, atk: 56, def: 48, speed: 58, morale: 58, range: 50, vision: 72,
    personality: { aggressiveness: 58, caution: 38, discipline: 45, greed: 50, loyalty: 48 },
    skills: ['charge'] }),
  g({ id: 'y_jiangqi', name: '蒋奇', faction: 'yuan', troopType: 'spearman', rarity: 'normal', color: YUAN,
    command: 52, strategy: 40, politics: 30, martial: 65, achievement: 30, charisma: 38,
    hp: 840, atk: 62, def: 55, speed: 48, morale: 62, range: 50, vision: 78,
    personality: { aggressiveness: 58, caution: 40, discipline: 52, greed: 38, loyalty: 58 },
    skills: ['fortify'] }),
  g({ id: 'y_hanlv', name: '韩猛', faction: 'yuan', troopType: 'cavalry', rarity: 'normal', color: YUAN,
    command: 48, strategy: 32, politics: 25, martial: 68, achievement: 28, charisma: 35,
    hp: 850, atk: 65, def: 48, speed: 60, morale: 62, range: 50, vision: 75,
    personality: { aggressiveness: 72, caution: 22, discipline: 42, greed: 45, loyalty: 55 },
    skills: ['charge'] }),
  g({ id: 'y_liufuren', name: '刘夫人', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 32, strategy: 55, politics: 62, martial: 15, achievement: 25, charisma: 65,
    hp: 450, atk: 18, def: 28, speed: 38, morale: 70, range: 50, vision: 88,
    personality: { aggressiveness: 10, caution: 88, discipline: 68, greed: 55, loyalty: 72 },
    skills: ['heal', 'rally'] }),
]
