import { General } from '../types'
import { SKILLS } from './skills'

const s = SKILLS

function g(
  partial: Omit<General, 'skills' | 'tags'> & { skills?: string[]; tags?: string[] }
): General {
  return { ...partial, skills: (partial.skills ?? []).map((id) => s[id]).filter(Boolean), tags: partial.tags ?? [] }
}

// Colors for new factions
const DONG = '#8b3a3a'   // 暗红
const YUAN = '#7a6abf'   // 紫
const XILIANG = '#bf8a3a' // 金沙
const JINGZHOU = '#5a8a6a' // 青绿
const YIZHOU = '#6a7a3a'  // 橄榄
const JIN = '#8a8abf'    // 银蓝

// ===================================================================
// 董卓势力 — 暴虐军团
// ===================================================================
export const DONG_GENERALS: General[] = [
  g({ id: 'd_dongzhuo', name: '董卓', faction: 'dong', troopType: 'cavalry', rarity: 'elite', color: DONG,
    command: 75, strategy: 55, politics: 50, martial: 78, achievement: 72, charisma: 30,
    hp: 950, atk: 75, def: 60, speed: 50, morale: 65, range: 50, vision: 85,
    personality: { aggressiveness: 80, caution: 30, discipline: 40, greed: 95, loyalty: 15 },
    skills: ['roar', 'inspire'] }),
  g({ id: 'd_lvbu', name: '吕布', faction: 'dong', troopType: 'cavalry', rarity: 'legend', color: DONG,
    command: 70, strategy: 40, politics: 20, martial: 100, achievement: 72, charisma: 45,
    hp: 1200, atk: 98, def: 65, speed: 75, morale: 65, range: 50, vision: 85,
    personality: { aggressiveness: 98, caution: 5, discipline: 20, greed: 90, loyalty: 10 },
    skills: ['duel', 'charge'] }),
  g({ id: 'd_libu', name: '李傕', faction: 'dong', troopType: 'cavalry', rarity: 'normal', color: DONG,
    command: 62, strategy: 42, politics: 35, martial: 72, achievement: 45, charisma: 25,
    hp: 880, atk: 70, def: 52, speed: 60, morale: 60, range: 50, vision: 80,
    personality: { aggressiveness: 85, caution: 15, discipline: 30, greed: 90, loyalty: 20 },
    skills: ['charge'] }),
  g({ id: 'd_guosi', name: '郭汜', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 58, strategy: 38, politics: 30, martial: 70, achievement: 40, charisma: 22,
    hp: 860, atk: 68, def: 55, speed: 52, morale: 58, range: 50, vision: 78,
    personality: { aggressiveness: 82, caution: 18, discipline: 28, greed: 88, loyalty: 18 },
    skills: ['roar'] }),
  g({ id: 'd_huaxiong', name: '华雄', faction: 'dong', troopType: 'cavalry', rarity: 'elite', color: DONG,
    command: 60, strategy: 35, politics: 22, martial: 85, achievement: 42, charisma: 38,
    hp: 980, atk: 82, def: 55, speed: 60, morale: 68, range: 50, vision: 75,
    personality: { aggressiveness: 92, caution: 8, discipline: 40, greed: 65, loyalty: 55 },
    skills: ['duel'] }),
  g({ id: 'd_niufu', name: '牛辅', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 52, strategy: 30, politics: 25, martial: 65, achievement: 32, charisma: 20,
    hp: 820, atk: 62, def: 50, speed: 48, morale: 55, range: 50, vision: 75,
    personality: { aggressiveness: 70, caution: 25, discipline: 35, greed: 75, loyalty: 30 },
    skills: ['fortify'] }),
  g({ id: 'd_zhangji', name: '张济', faction: 'dong', troopType: 'spearman', rarity: 'normal', color: DONG,
    command: 58, strategy: 40, politics: 35, martial: 68, achievement: 38, charisma: 35,
    hp: 860, atk: 65, def: 55, speed: 50, morale: 62, range: 50, vision: 80,
    personality: { aggressiveness: 60, caution: 40, discipline: 50, greed: 60, loyalty: 40 },
    skills: ['fortify'] }),
  g({ id: 'd_gaoshun', name: '高顺', faction: 'dong', troopType: 'spearman', rarity: 'elite', color: DONG,
    command: 82, strategy: 58, politics: 42, martial: 82, achievement: 60, charisma: 65,
    hp: 980, atk: 78, def: 72, speed: 48, morale: 88, range: 50, vision: 88,
    personality: { aggressiveness: 65, caution: 45, discipline: 95, greed: 10, loyalty: 95 },
    skills: ['fortify', 'charge'] }),
  g({ id: 'd_chenggong', name: '陈宫', faction: 'dong', troopType: 'archer', rarity: 'elite', color: DONG,
    command: 70, strategy: 90, politics: 72, martial: 35, achievement: 60, charisma: 72,
    hp: 650, atk: 42, def: 45, speed: 48, morale: 80, range: 140, vision: 125,
    personality: { aggressiveness: 45, caution: 70, discipline: 78, greed: 20, loyalty: 90 },
    skills: ['stratagem', 'fire_attack'] }),
  g({ id: 'd_lijue2', name: '李儒', faction: 'dong', troopType: 'archer', rarity: 'elite', color: DONG,
    command: 55, strategy: 85, politics: 70, martial: 28, achievement: 48, charisma: 30,
    hp: 580, atk: 38, def: 35, speed: 45, morale: 65, range: 140, vision: 120,
    personality: { aggressiveness: 40, caution: 80, discipline: 70, greed: 50, loyalty: 60 },
    skills: ['fire_attack', 'stratagem'] }),
  // 补充
  g({ id: 'd_fandchou', name: '樊稠', faction: 'dong', troopType: 'cavalry', rarity: 'normal', color: DONG,
    command: 55, strategy: 35, politics: 28, martial: 68, achievement: 32, charisma: 30,
    hp: 840, atk: 65, def: 50, speed: 58, morale: 58, range: 50, vision: 78,
    personality: { aggressiveness: 75, caution: 20, discipline: 35, greed: 70, loyalty: 25 },
    skills: ['charge'] }),
  g({ id: 'd_diaochan', name: '貂蝉', faction: 'dong', troopType: 'infantry', rarity: 'elite', color: DONG,
    command: 30, strategy: 80, politics: 72, martial: 18, achievement: 55, charisma: 95,
    hp: 420, atk: 20, def: 25, speed: 45, morale: 90, range: 50, vision: 100,
    personality: { aggressiveness: 10, caution: 90, discipline: 80, greed: 10, loyalty: 50 },
    skills: ['inspire', 'rally'] }),
  g({ id: 'd_houchen', name: '侯成', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 48, strategy: 32, politics: 25, martial: 62, achievement: 28, charisma: 28,
    hp: 800, atk: 58, def: 48, speed: 48, morale: 50, range: 50, vision: 72,
    personality: { aggressiveness: 55, caution: 45, discipline: 38, greed: 60, loyalty: 20 },
    skills: ['fortify'] }),
  g({ id: 'd_songjian', name: '宋宪', faction: 'dong', troopType: 'spearman', rarity: 'normal', color: DONG,
    command: 45, strategy: 28, politics: 22, martial: 60, achievement: 25, charisma: 25,
    hp: 790, atk: 56, def: 48, speed: 46, morale: 48, range: 50, vision: 70,
    personality: { aggressiveness: 52, caution: 48, discipline: 35, greed: 58, loyalty: 18 },
    skills: ['fortify'] }),
  g({ id: 'd_weixu', name: '魏续', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 42, strategy: 25, politics: 20, martial: 58, achievement: 22, charisma: 22,
    hp: 780, atk: 55, def: 45, speed: 45, morale: 46, range: 50, vision: 68,
    personality: { aggressiveness: 50, caution: 50, discipline: 32, greed: 55, loyalty: 15 },
    skills: ['ambush'] }),
  g({ id: 'd_caodeng', name: '曹性', faction: 'dong', troopType: 'archer', rarity: 'normal', color: DONG,
    command: 42, strategy: 35, politics: 22, martial: 65, achievement: 25, charisma: 28,
    hp: 760, atk: 62, def: 40, speed: 48, morale: 55, range: 150, vision: 90,
    personality: { aggressiveness: 55, caution: 40, discipline: 42, greed: 40, loyalty: 50 },
    skills: ['snipe'] }),
  g({ id: 'd_zhangxiu2', name: '张绣', faction: 'dong', troopType: 'cavalry', rarity: 'normal', color: DONG,
    command: 70, strategy: 58, politics: 42, martial: 80, achievement: 55, charisma: 50,
    hp: 900, atk: 75, def: 55, speed: 62, morale: 70, range: 50, vision: 88,
    personality: { aggressiveness: 72, caution: 40, discipline: 55, greed: 60, loyalty: 45 },
    skills: ['ambush', 'charge'] }),
  g({ id: 'd_yanliangd', name: '严氏', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 35, strategy: 48, politics: 55, martial: 18, achievement: 20, charisma: 62,
    hp: 450, atk: 22, def: 30, speed: 38, morale: 68, range: 50, vision: 85,
    personality: { aggressiveness: 8, caution: 90, discipline: 72, greed: 8, loyalty: 88 },
    skills: ['heal'] }),
  g({ id: 'd_lilingqi', name: '吕玲绮', faction: 'dong', troopType: 'cavalry', rarity: 'elite', color: DONG,
    command: 55, strategy: 45, politics: 30, martial: 82, achievement: 35, charisma: 65,
    hp: 880, atk: 78, def: 50, speed: 70, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 78, caution: 25, discipline: 55, greed: 15, loyalty: 88 },
    skills: ['charge', 'duel'] }),
  g({ id: 'd_zangba', name: '臧霸', faction: 'dong', troopType: 'infantry', rarity: 'normal', color: DONG,
    command: 65, strategy: 50, politics: 42, martial: 72, achievement: 48, charisma: 55,
    hp: 880, atk: 68, def: 58, speed: 50, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 62, caution: 38, discipline: 58, greed: 35, loyalty: 55 },
    skills: ['fortify', 'charge'] }),
]

// ===================================================================
// 袁绍势力 — 河北四州
// ===================================================================
export const YUAN_GENERALS: General[] = [
  g({ id: 'y_yuanshao', name: '袁绍', faction: 'yuan', troopType: 'cavalry', rarity: 'elite', color: YUAN,
    command: 72, strategy: 60, politics: 70, martial: 55, achievement: 75, charisma: 72,
    hp: 850, atk: 55, def: 58, speed: 50, morale: 78, range: 50, vision: 100,
    personality: { aggressiveness: 55, caution: 60, discipline: 60, greed: 70, loyalty: 50 },
    skills: ['inspire', 'rally'] }),
  g({ id: 'y_yanliang', name: '颜良', faction: 'yuan', troopType: 'cavalry', rarity: 'elite', color: YUAN,
    command: 68, strategy: 38, politics: 25, martial: 92, achievement: 55, charisma: 48,
    hp: 1050, atk: 88, def: 58, speed: 65, morale: 75, range: 50, vision: 78,
    personality: { aggressiveness: 92, caution: 10, discipline: 55, greed: 50, loyalty: 72 },
    skills: ['charge', 'duel'] }),
  g({ id: 'y_wenchou', name: '文丑', faction: 'yuan', troopType: 'cavalry', rarity: 'elite', color: YUAN,
    command: 65, strategy: 35, politics: 22, martial: 90, achievement: 52, charisma: 45,
    hp: 1020, atk: 86, def: 55, speed: 62, morale: 72, range: 50, vision: 75,
    personality: { aggressiveness: 90, caution: 12, discipline: 50, greed: 55, loyalty: 70 },
    skills: ['duel', 'roar'] }),
  g({ id: 'y_tianfeng', name: '田丰', faction: 'yuan', troopType: 'infantry', rarity: 'elite', color: YUAN,
    command: 68, strategy: 88, politics: 80, martial: 30, achievement: 58, charisma: 70,
    hp: 640, atk: 40, def: 48, speed: 42, morale: 82, range: 50, vision: 120,
    personality: { aggressiveness: 30, caution: 90, discipline: 88, greed: 10, loyalty: 95 },
    skills: ['stratagem', 'heal'] }),
  g({ id: 'y_jushou', name: '沮授', faction: 'yuan', troopType: 'shield', rarity: 'elite', color: YUAN,
    command: 78, strategy: 85, politics: 78, martial: 38, achievement: 60, charisma: 75,
    hp: 700, atk: 42, def: 55, speed: 42, morale: 85, range: 50, vision: 115,
    personality: { aggressiveness: 30, caution: 82, discipline: 85, greed: 12, loyalty: 92 },
    skills: ['fortify', 'rally'] }),
  g({ id: 'y_guotu', name: '郭图', faction: 'yuan', troopType: 'archer', rarity: 'normal', color: YUAN,
    command: 48, strategy: 72, politics: 65, martial: 25, achievement: 35, charisma: 35,
    hp: 580, atk: 35, def: 38, speed: 42, morale: 60, range: 130, vision: 100,
    personality: { aggressiveness: 55, caution: 55, discipline: 40, greed: 75, loyalty: 40 },
    skills: ['stratagem'] }),
  g({ id: 'y_zhanghe2', name: '张郃', faction: 'yuan', troopType: 'spearman', rarity: 'elite', color: YUAN,
    command: 80, strategy: 70, politics: 45, martial: 82, achievement: 72, charisma: 68,
    hp: 920, atk: 75, def: 68, speed: 55, morale: 82, range: 50, vision: 95,
    personality: { aggressiveness: 65, caution: 55, discipline: 75, greed: 45, loyalty: 70 },
    skills: ['ambush'] }),
  g({ id: 'y_gaolan', name: '高览', faction: 'yuan', troopType: 'shield', rarity: 'normal', color: YUAN,
    command: 68, strategy: 52, politics: 40, martial: 76, achievement: 48, charisma: 55,
    hp: 920, atk: 70, def: 70, speed: 45, morale: 75, range: 50, vision: 85,
    personality: { aggressiveness: 55, caution: 50, discipline: 72, greed: 40, loyalty: 60 },
    skills: ['shield_wall'] }),
  g({ id: 'y_chunyuqiong', name: '淳于琼', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 55, strategy: 35, politics: 40, martial: 60, achievement: 35, charisma: 40,
    hp: 800, atk: 55, def: 50, speed: 42, morale: 55, range: 50, vision: 80,
    personality: { aggressiveness: 45, caution: 50, discipline: 30, greed: 60, loyalty: 50 },
    skills: ['fortify'] }),
  g({ id: 'y_yuantan', name: '袁谭', faction: 'yuan', troopType: 'cavalry', rarity: 'normal', color: YUAN,
    command: 55, strategy: 48, politics: 50, martial: 58, achievement: 40, charisma: 42,
    hp: 780, atk: 55, def: 48, speed: 55, morale: 62, range: 50, vision: 85,
    personality: { aggressiveness: 60, caution: 40, discipline: 45, greed: 70, loyalty: 35 },
    skills: ['charge'] }),
  // 补充
  g({ id: 'y_yuanxi', name: '袁熙', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 52, strategy: 45, politics: 48, martial: 52, achievement: 35, charisma: 40,
    hp: 740, atk: 50, def: 48, speed: 48, morale: 58, range: 50, vision: 82,
    personality: { aggressiveness: 42, caution: 55, discipline: 50, greed: 55, loyalty: 45 },
    skills: ['fortify'] }),
  g({ id: 'y_yuanshang', name: '袁尚', faction: 'yuan', troopType: 'cavalry', rarity: 'normal', color: YUAN,
    command: 50, strategy: 50, politics: 52, martial: 55, achievement: 38, charisma: 45,
    hp: 760, atk: 52, def: 48, speed: 55, morale: 60, range: 50, vision: 82,
    personality: { aggressiveness: 55, caution: 45, discipline: 42, greed: 72, loyalty: 32 },
    skills: ['charge'] }),
  g({ id: 'y_xupei', name: '许攸', faction: 'yuan', troopType: 'archer', rarity: 'elite', color: YUAN,
    command: 42, strategy: 82, politics: 68, martial: 22, achievement: 45, charisma: 28,
    hp: 520, atk: 30, def: 32, speed: 42, morale: 55, range: 130, vision: 115,
    personality: { aggressiveness: 45, caution: 55, discipline: 30, greed: 90, loyalty: 15 },
    skills: ['stratagem', 'ambush'] }),
  g({ id: 'y_fengji', name: '逢纪', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 45, strategy: 68, politics: 62, martial: 22, achievement: 32, charisma: 35,
    hp: 560, atk: 28, def: 35, speed: 40, morale: 60, range: 50, vision: 95,
    personality: { aggressiveness: 35, caution: 65, discipline: 55, greed: 60, loyalty: 50 },
    skills: ['stratagem'] }),
  g({ id: 'y_shenpei', name: '审配', faction: 'yuan', troopType: 'shield', rarity: 'elite', color: YUAN,
    command: 72, strategy: 68, politics: 70, martial: 45, achievement: 52, charisma: 68,
    hp: 780, atk: 48, def: 65, speed: 42, morale: 82, range: 50, vision: 95,
    personality: { aggressiveness: 40, caution: 68, discipline: 85, greed: 15, loyalty: 95 },
    skills: ['fortify', 'shield_wall'] }),
  g({ id: 'y_lvkuang', name: '吕旷', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 50, strategy: 38, politics: 32, martial: 62, achievement: 28, charisma: 35,
    hp: 800, atk: 58, def: 50, speed: 48, morale: 60, range: 50, vision: 75,
    personality: { aggressiveness: 55, caution: 42, discipline: 48, greed: 48, loyalty: 50 },
    skills: ['fortify'] }),
  g({ id: 'y_lvxiang', name: '吕翔', faction: 'yuan', troopType: 'cavalry', rarity: 'normal', color: YUAN,
    command: 48, strategy: 35, politics: 28, martial: 60, achievement: 25, charisma: 32,
    hp: 790, atk: 56, def: 48, speed: 58, morale: 58, range: 50, vision: 72,
    personality: { aggressiveness: 58, caution: 38, discipline: 45, greed: 50, loyalty: 48 },
    skills: ['charge'] }),
  g({ id: 'y_jiangqi', name: '蒋奇', faction: 'yuan', troopType: 'spearman', rarity: 'normal', color: YUAN,
    command: 52, strategy: 40, politics: 30, martial: 65, achievement: 30, charisma: 38,
    hp: 840, atk: 62, def: 55, speed: 48, morale: 62, range: 50, vision: 78,
    personality: { aggressiveness: 58, caution: 40, discipline: 52, greed: 38, loyalty: 58 },
    skills: ['fortify'] }),
  g({ id: 'y_hanlv', name: '韩猛', faction: 'yuan', troopType: 'cavalry', rarity: 'normal', color: YUAN,
    command: 48, strategy: 32, politics: 25, martial: 68, achievement: 28, charisma: 35,
    hp: 850, atk: 65, def: 48, speed: 60, morale: 62, range: 50, vision: 75,
    personality: { aggressiveness: 72, caution: 22, discipline: 42, greed: 45, loyalty: 55 },
    skills: ['charge'] }),
  g({ id: 'y_liufuren', name: '刘夫人', faction: 'yuan', troopType: 'infantry', rarity: 'normal', color: YUAN,
    command: 32, strategy: 55, politics: 62, martial: 15, achievement: 25, charisma: 65,
    hp: 450, atk: 18, def: 28, speed: 38, morale: 70, range: 50, vision: 88,
    personality: { aggressiveness: 10, caution: 88, discipline: 68, greed: 55, loyalty: 72 },
    skills: ['heal', 'rally'] }),
]
// ===================================================================
export const XILIANG_GENERALS: General[] = [
  g({ id: 'xl_mateng', name: '马腾', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 78, strategy: 55, politics: 55, martial: 82, achievement: 62, charisma: 72,
    hp: 950, atk: 78, def: 58, speed: 62, morale: 80, range: 50, vision: 92,
    personality: { aggressiveness: 68, caution: 40, discipline: 65, greed: 40, loyalty: 82 },
    skills: ['charge', 'inspire'] }),
  g({ id: 'xl_hansui', name: '韩遂', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 72, strategy: 68, politics: 65, martial: 68, achievement: 58, charisma: 55,
    hp: 850, atk: 65, def: 55, speed: 58, morale: 68, range: 50, vision: 90,
    personality: { aggressiveness: 55, caution: 55, discipline: 50, greed: 70, loyalty: 30 },
    skills: ['stratagem', 'ambush'] }),
  g({ id: 'xl_machao2', name: '马超', faction: 'xiliang', troopType: 'cavalry', rarity: 'legend', color: XILIANG,
    command: 75, strategy: 50, politics: 35, martial: 95, achievement: 72, charisma: 65,
    hp: 1000, atk: 90, def: 58, speed: 72, morale: 78, range: 50, vision: 90,
    personality: { aggressiveness: 92, caution: 15, discipline: 50, greed: 70, loyalty: 55 },
    skills: ['charge', 'duel'] }),
  g({ id: 'xl_madai2', name: '马岱', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 68, strategy: 55, politics: 40, martial: 76, achievement: 52, charisma: 55,
    hp: 880, atk: 72, def: 55, speed: 65, morale: 76, range: 50, vision: 85,
    personality: { aggressiveness: 65, caution: 42, discipline: 68, greed: 35, loyalty: 82 },
    skills: ['ambush'] }),
  g({ id: 'xl_pangde2', name: '庞德', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 70, strategy: 48, politics: 35, martial: 90, achievement: 60, charisma: 68,
    hp: 1000, atk: 85, def: 58, speed: 62, morale: 90, range: 50, vision: 80,
    personality: { aggressiveness: 88, caution: 12, discipline: 72, greed: 30, loyalty: 92 },
    skills: ['duel', 'charge'] }),
  g({ id: 'xl_chengyi', name: '成宜', faction: 'xiliang', troopType: 'spearman', rarity: 'normal', color: XILIANG,
    command: 55, strategy: 38, politics: 30, martial: 68, achievement: 35, charisma: 42,
    hp: 850, atk: 65, def: 55, speed: 52, morale: 65, range: 50, vision: 78,
    personality: { aggressiveness: 72, caution: 28, discipline: 45, greed: 50, loyalty: 55 },
    skills: ['charge'] }),
  g({ id: 'xl_yanxing', name: '阎行', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 62, strategy: 45, politics: 32, martial: 85, achievement: 45, charisma: 48,
    hp: 920, atk: 80, def: 52, speed: 68, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 82, caution: 20, discipline: 55, greed: 45, loyalty: 60 },
    skills: ['duel'] }),
  g({ id: 'xl_liangxing', name: '梁兴', faction: 'xiliang', troopType: 'infantry', rarity: 'normal', color: XILIANG,
    command: 52, strategy: 35, politics: 28, martial: 65, achievement: 32, charisma: 38,
    hp: 820, atk: 62, def: 52, speed: 50, morale: 62, range: 50, vision: 76,
    personality: { aggressiveness: 68, caution: 30, discipline: 42, greed: 55, loyalty: 48 },
    skills: ['fortify'] }),
  // 补充
  g({ id: 'xl_matai', name: '马铁', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 50, strategy: 35, politics: 28, martial: 65, achievement: 28, charisma: 42,
    hp: 830, atk: 62, def: 48, speed: 62, morale: 68, range: 50, vision: 78,
    personality: { aggressiveness: 65, caution: 32, discipline: 55, greed: 30, loyalty: 85 },
    skills: ['charge'] }),
  g({ id: 'xl_mawan', name: '马玩', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 32, politics: 25, martial: 62, achievement: 25, charisma: 35,
    hp: 810, atk: 60, def: 45, speed: 60, morale: 60, range: 50, vision: 75,
    personality: { aggressiveness: 70, caution: 25, discipline: 40, greed: 50, loyalty: 45 },
    skills: ['charge'] }),
  g({ id: 'xl_houxuan', name: '侯选', faction: 'xiliang', troopType: 'spearman', rarity: 'normal', color: XILIANG,
    command: 50, strategy: 35, politics: 30, martial: 62, achievement: 28, charisma: 35,
    hp: 830, atk: 58, def: 55, speed: 48, morale: 60, range: 50, vision: 75,
    personality: { aggressiveness: 58, caution: 38, discipline: 48, greed: 48, loyalty: 42 },
    skills: ['fortify'] }),
  g({ id: 'xl_chengyin', name: '程银', faction: 'xiliang', troopType: 'infantry', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 32, politics: 25, martial: 60, achievement: 25, charisma: 32,
    hp: 800, atk: 58, def: 50, speed: 48, morale: 58, range: 50, vision: 72,
    personality: { aggressiveness: 62, caution: 32, discipline: 40, greed: 52, loyalty: 40 },
    skills: ['ambush'] }),
  g({ id: 'xl_yangqiu', name: '杨秋', faction: 'xiliang', troopType: 'archer', rarity: 'normal', color: XILIANG,
    command: 52, strategy: 42, politics: 35, martial: 58, achievement: 28, charisma: 38,
    hp: 760, atk: 55, def: 42, speed: 48, morale: 60, range: 140, vision: 88,
    personality: { aggressiveness: 50, caution: 48, discipline: 45, greed: 45, loyalty: 42 },
    skills: ['snipe'] }),
  g({ id: 'xl_zhangheng', name: '张横', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 30, politics: 22, martial: 64, achievement: 25, charisma: 30,
    hp: 820, atk: 62, def: 48, speed: 62, morale: 58, range: 50, vision: 75,
    personality: { aggressiveness: 72, caution: 22, discipline: 38, greed: 52, loyalty: 38 },
    skills: ['charge'] }),
  g({ id: 'xl_jiaxu', name: '贾诩', faction: 'xiliang', troopType: 'archer', rarity: 'legend', color: XILIANG,
    command: 68, strategy: 95, politics: 82, martial: 32, achievement: 72, charisma: 45,
    hp: 620, atk: 45, def: 42, speed: 48, morale: 72, range: 140, vision: 135,
    personality: { aggressiveness: 30, caution: 95, discipline: 80, greed: 50, loyalty: 35 },
    skills: ['fire_attack', 'ambush'] }),
  g({ id: 'xl_zhangxiu3', name: '张绣', faction: 'xiliang', troopType: 'cavalry', rarity: 'elite', color: XILIANG,
    command: 70, strategy: 58, politics: 42, martial: 80, achievement: 55, charisma: 50,
    hp: 900, atk: 75, def: 55, speed: 62, morale: 70, range: 50, vision: 88,
    personality: { aggressiveness: 72, caution: 40, discipline: 55, greed: 60, loyalty: 45 },
    skills: ['ambush', 'charge'] }),
  g({ id: 'xl_liwei', name: '李堪', faction: 'xiliang', troopType: 'infantry', rarity: 'normal', color: XILIANG,
    command: 45, strategy: 30, politics: 25, martial: 60, achievement: 22, charisma: 30,
    hp: 800, atk: 58, def: 48, speed: 48, morale: 55, range: 50, vision: 72,
    personality: { aggressiveness: 65, caution: 30, discipline: 38, greed: 50, loyalty: 42 },
    skills: ['fortify'] }),
  g({ id: 'xl_machengji', name: '马承', faction: 'xiliang', troopType: 'cavalry', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 35, politics: 28, martial: 62, achievement: 25, charisma: 40,
    hp: 820, atk: 60, def: 48, speed: 62, morale: 62, range: 50, vision: 75,
    personality: { aggressiveness: 60, caution: 35, discipline: 52, greed: 30, loyalty: 78 },
    skills: ['charge'] }),
  g({ id: 'xl_mazhong', name: '马忠', faction: 'xiliang', troopType: 'archer', rarity: 'normal', color: XILIANG,
    command: 50, strategy: 45, politics: 35, martial: 58, achievement: 30, charisma: 38,
    hp: 750, atk: 55, def: 42, speed: 48, morale: 60, range: 140, vision: 88,
    personality: { aggressiveness: 48, caution: 52, discipline: 50, greed: 38, loyalty: 55 },
    skills: ['snipe'] }),
  g({ id: 'xl_quanhui', name: '阙怀', faction: 'xiliang', troopType: 'shield', rarity: 'normal', color: XILIANG,
    command: 48, strategy: 32, politics: 28, martial: 58, achievement: 22, charisma: 35,
    hp: 850, atk: 52, def: 62, speed: 42, morale: 60, range: 50, vision: 72,
    personality: { aggressiveness: 40, caution: 55, discipline: 52, greed: 35, loyalty: 50 },
    skills: ['shield_wall'] }),
]

// ===================================================================
// 荆州 — 刘表
// ===================================================================
export const JINGZHOU_GENERALS: General[] = [
  g({ id: 'jz_liubiao', name: '刘表', faction: 'jingzhou', troopType: 'infantry', rarity: 'elite', color: JINGZHOU,
    command: 60, strategy: 62, politics: 78, martial: 35, achievement: 58, charisma: 68,
    hp: 720, atk: 42, def: 50, speed: 40, morale: 75, range: 50, vision: 95,
    personality: { aggressiveness: 20, caution: 85, discipline: 72, greed: 35, loyalty: 55 },
    skills: ['rally'] }),
  g({ id: 'jz_huangzu', name: '黄祖', faction: 'jingzhou', troopType: 'archer', rarity: 'normal', color: JINGZHOU,
    command: 55, strategy: 48, politics: 50, martial: 58, achievement: 40, charisma: 38,
    hp: 750, atk: 55, def: 48, speed: 42, morale: 62, range: 140, vision: 90,
    personality: { aggressiveness: 50, caution: 60, discipline: 55, greed: 55, loyalty: 60 },
    skills: ['snipe'] }),
  g({ id: 'jz_caimao', name: '蔡瑁', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 58, strategy: 55, politics: 62, martial: 45, achievement: 42, charisma: 35,
    hp: 720, atk: 48, def: 52, speed: 42, morale: 60, range: 50, vision: 85,
    personality: { aggressiveness: 35, caution: 70, discipline: 55, greed: 80, loyalty: 25 },
    skills: ['fortify'] }),
  g({ id: 'jz_kuaiyue', name: '蒯越', faction: 'jingzhou', troopType: 'archer', rarity: 'elite', color: JINGZHOU,
    command: 62, strategy: 82, politics: 78, martial: 32, achievement: 48, charisma: 55,
    hp: 620, atk: 40, def: 42, speed: 45, morale: 72, range: 140, vision: 110,
    personality: { aggressiveness: 30, caution: 80, discipline: 75, greed: 50, loyalty: 45 },
    skills: ['stratagem', 'heal'] }),
  g({ id: 'jz_wentai', name: '文聘', faction: 'jingzhou', troopType: 'shield', rarity: 'elite', color: JINGZHOU,
    command: 75, strategy: 62, politics: 55, martial: 78, achievement: 58, charisma: 70,
    hp: 950, atk: 70, def: 75, speed: 45, morale: 85, range: 50, vision: 88,
    personality: { aggressiveness: 50, caution: 60, discipline: 88, greed: 15, loyalty: 90 },
    skills: ['shield_wall', 'fortify'] }),
  g({ id: 'jz_huangzhong2', name: '黄忠', faction: 'jingzhou', troopType: 'archer', rarity: 'elite', color: JINGZHOU,
    command: 72, strategy: 55, politics: 40, martial: 88, achievement: 68, charisma: 60,
    hp: 850, atk: 82, def: 55, speed: 45, morale: 85, range: 180, vision: 120,
    personality: { aggressiveness: 65, caution: 45, discipline: 80, greed: 40, loyalty: 90 },
    skills: ['snipe'] }),
  g({ id: 'jz_weiyan2', name: '魏延', faction: 'jingzhou', troopType: 'infantry', rarity: 'elite', color: JINGZHOU,
    command: 80, strategy: 68, politics: 38, martial: 88, achievement: 70, charisma: 45,
    hp: 980, atk: 82, def: 62, speed: 55, morale: 72, range: 50, vision: 90,
    personality: { aggressiveness: 85, caution: 25, discipline: 45, greed: 80, loyalty: 35 },
    skills: ['ambush', 'charge'] }),
  g({ id: 'jz_ganfu', name: '甘夫人', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 40, strategy: 55, politics: 65, martial: 20, achievement: 30, charisma: 78,
    hp: 500, atk: 25, def: 35, speed: 40, morale: 80, range: 50, vision: 90,
    personality: { aggressiveness: 10, caution: 90, discipline: 85, greed: 5, loyalty: 100 },
    skills: ['heal', 'rally'] }),
  // 补充
  g({ id: 'jz_liuqi', name: '刘琦', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 45, strategy: 42, politics: 50, martial: 35, achievement: 32, charisma: 48,
    hp: 650, atk: 38, def: 42, speed: 40, morale: 62, range: 50, vision: 82,
    personality: { aggressiveness: 25, caution: 72, discipline: 55, greed: 25, loyalty: 70 },
    skills: ['rally'] }),
  g({ id: 'jz_liucong', name: '刘琮', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 35, strategy: 38, politics: 42, martial: 25, achievement: 28, charisma: 35,
    hp: 580, atk: 30, def: 38, speed: 38, morale: 50, range: 50, vision: 78,
    personality: { aggressiveness: 12, caution: 88, discipline: 42, greed: 40, loyalty: 30 },
    skills: ['fortify'] }),
  g({ id: 'jz_yiji', name: '伊籍', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 42, strategy: 65, politics: 72, martial: 22, achievement: 35, charisma: 62,
    hp: 560, atk: 28, def: 35, speed: 42, morale: 70, range: 50, vision: 95,
    personality: { aggressiveness: 18, caution: 78, discipline: 72, greed: 12, loyalty: 82 },
    skills: ['heal', 'inspire'] }),
  g({ id: 'jz_huangsha', name: '霍峻', faction: 'jingzhou', troopType: 'shield', rarity: 'elite', color: JINGZHOU,
    command: 72, strategy: 58, politics: 50, martial: 72, achievement: 48, charisma: 62,
    hp: 920, atk: 65, def: 72, speed: 42, morale: 82, range: 50, vision: 85,
    personality: { aggressiveness: 42, caution: 65, discipline: 85, greed: 10, loyalty: 92 },
    skills: ['fortify', 'shield_wall'] }),
  g({ id: 'jz_xingdaorong', name: '邢道荣', faction: 'jingzhou', troopType: 'spearman', rarity: 'normal', color: JINGZHOU,
    command: 42, strategy: 25, politics: 18, martial: 70, achievement: 20, charisma: 30,
    hp: 860, atk: 68, def: 52, speed: 48, morale: 55, range: 50, vision: 72,
    personality: { aggressiveness: 78, caution: 15, discipline: 35, greed: 50, loyalty: 45 },
    skills: ['charge'] }),
  g({ id: 'jz_wangwei', name: '王威', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 58, strategy: 52, politics: 48, martial: 62, achievement: 35, charisma: 55,
    hp: 820, atk: 58, def: 55, speed: 45, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 55, caution: 52, discipline: 70, greed: 18, loyalty: 85 },
    skills: ['fortify'] }),
  g({ id: 'jz_dengyi', name: '邓义', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 48, strategy: 52, politics: 58, martial: 35, achievement: 28, charisma: 42,
    hp: 650, atk: 38, def: 42, speed: 42, morale: 62, range: 50, vision: 85,
    personality: { aggressiveness: 25, caution: 72, discipline: 62, greed: 35, loyalty: 55 },
    skills: ['heal'] }),
  g({ id: 'jz_liupan', name: '刘磐', faction: 'jingzhou', troopType: 'cavalry', rarity: 'normal', color: JINGZHOU,
    command: 55, strategy: 42, politics: 38, martial: 68, achievement: 35, charisma: 45,
    hp: 850, atk: 65, def: 52, speed: 58, morale: 68, range: 50, vision: 80,
    personality: { aggressiveness: 65, caution: 35, discipline: 55, greed: 35, loyalty: 65 },
    skills: ['charge'] }),
  g({ id: 'jz_zhangyan', name: '张允', faction: 'jingzhou', troopType: 'archer', rarity: 'normal', color: JINGZHOU,
    command: 52, strategy: 48, politics: 52, martial: 42, achievement: 30, charisma: 35,
    hp: 700, atk: 48, def: 42, speed: 45, morale: 55, range: 140, vision: 88,
    personality: { aggressiveness: 35, caution: 62, discipline: 48, greed: 60, loyalty: 32 },
    skills: ['snipe'] }),
  g({ id: 'jz_fuquan', name: '傅巽', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 38, strategy: 62, politics: 68, martial: 20, achievement: 28, charisma: 50,
    hp: 540, atk: 25, def: 32, speed: 40, morale: 62, range: 50, vision: 90,
    personality: { aggressiveness: 15, caution: 82, discipline: 65, greed: 48, loyalty: 35 },
    skills: ['stratagem'] }),
  g({ id: 'jz_huojun', name: '霍笃', faction: 'jingzhou', troopType: 'spearman', rarity: 'normal', color: JINGZHOU,
    command: 55, strategy: 42, politics: 38, martial: 65, achievement: 32, charisma: 48,
    hp: 850, atk: 62, def: 58, speed: 45, morale: 70, range: 50, vision: 78,
    personality: { aggressiveness: 50, caution: 48, discipline: 72, greed: 18, loyalty: 82 },
    skills: ['fortify'] }),
  g({ id: 'jz_hanxi', name: '韩嵩', faction: 'jingzhou', troopType: 'infantry', rarity: 'normal', color: JINGZHOU,
    command: 42, strategy: 65, politics: 72, martial: 22, achievement: 35, charisma: 58,
    hp: 560, atk: 28, def: 35, speed: 42, morale: 68, range: 50, vision: 92,
    personality: { aggressiveness: 12, caution: 85, discipline: 75, greed: 12, loyalty: 78 },
    skills: ['heal', 'inspire'] }),
]

// =================================================================== — 刘璋
// ===================================================================
export const YIZHOU_GENERALS: General[] = [
  g({ id: 'yz_liuzhang', name: '刘璋', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 42, strategy: 45, politics: 58, martial: 28, achievement: 40, charisma: 52,
    hp: 650, atk: 35, def: 42, speed: 38, morale: 60, range: 50, vision: 85,
    personality: { aggressiveness: 15, caution: 90, discipline: 55, greed: 30, loyalty: 50 },
    skills: ['rally'] }),
  g({ id: 'yz_zhangren2', name: '张任', faction: 'yizhou', troopType: 'archer', rarity: 'elite', color: YIZHOU,
    command: 72, strategy: 65, politics: 48, martial: 78, achievement: 48, charisma: 62,
    hp: 860, atk: 72, def: 58, speed: 50, morale: 82, range: 150, vision: 100,
    personality: { aggressiveness: 58, caution: 55, discipline: 78, greed: 18, loyalty: 90 },
    skills: ['snipe', 'ambush'] }),
  g({ id: 'yz_yanyan2', name: '严颜', faction: 'yizhou', troopType: 'shield', rarity: 'elite', color: YIZHOU,
    command: 70, strategy: 52, politics: 48, martial: 75, achievement: 50, charisma: 68,
    hp: 950, atk: 65, def: 72, speed: 40, morale: 85, range: 50, vision: 80,
    personality: { aggressiveness: 45, caution: 60, discipline: 82, greed: 15, loyalty: 90 },
    skills: ['fortify', 'shield_wall'] }),
  g({ id: 'yz_wuyi', name: '吴懿', faction: 'yizhou', troopType: 'cavalry', rarity: 'normal', color: YIZHOU,
    command: 62, strategy: 48, politics: 52, martial: 65, achievement: 42, charisma: 55,
    hp: 850, atk: 62, def: 55, speed: 58, morale: 68, range: 50, vision: 82,
    personality: { aggressiveness: 50, caution: 55, discipline: 65, greed: 35, loyalty: 65 },
    skills: ['charge'] }),
  g({ id: 'yz_fazheng2', name: '法正', faction: 'yizhou', troopType: 'archer', rarity: 'elite', color: YIZHOU,
    command: 65, strategy: 92, politics: 78, martial: 40, achievement: 70, charisma: 55,
    hp: 680, atk: 48, def: 45, speed: 48, morale: 75, range: 140, vision: 125,
    personality: { aggressiveness: 55, caution: 65, discipline: 60, greed: 60, loyalty: 80 },
    skills: ['ambush', 'stratagem'] }),
  g({ id: 'yz_mengda', name: '孟达', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 55, strategy: 58, politics: 52, martial: 62, achievement: 38, charisma: 35,
    hp: 780, atk: 58, def: 50, speed: 50, morale: 55, range: 50, vision: 85,
    personality: { aggressiveness: 50, caution: 60, discipline: 40, greed: 70, loyalty: 20 },
    skills: ['ambush'] }),
  g({ id: 'yz_huangquan', name: '黄权', faction: 'yizhou', troopType: 'infantry', rarity: 'elite', color: YIZHOU,
    command: 72, strategy: 78, politics: 72, martial: 45, achievement: 52, charisma: 68,
    hp: 720, atk: 48, def: 55, speed: 45, morale: 78, range: 50, vision: 100,
    personality: { aggressiveness: 35, caution: 75, discipline: 82, greed: 15, loyalty: 85 },
    skills: ['stratagem', 'fortify'] }),
  g({ id: 'yz_leiton', name: '雷铜', faction: 'yizhou', troopType: 'spearman', rarity: 'normal', color: YIZHOU,
    command: 52, strategy: 38, politics: 30, martial: 68, achievement: 32, charisma: 40,
    hp: 850, atk: 65, def: 58, speed: 48, morale: 65, range: 50, vision: 78,
    personality: { aggressiveness: 62, caution: 40, discipline: 55, greed: 35, loyalty: 70 },
    skills: ['fortify'] }),
  // 补充
  g({ id: 'yz_zhanglu', name: '张鲁', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 55, strategy: 55, politics: 62, martial: 38, achievement: 45, charisma: 65,
    hp: 700, atk: 42, def: 48, speed: 42, morale: 72, range: 50, vision: 85,
    personality: { aggressiveness: 25, caution: 72, discipline: 60, greed: 35, loyalty: 55 },
    skills: ['rally', 'heal'] }),
  g({ id: 'yz_yanghuai', name: '杨怀', faction: 'yizhou', troopType: 'spearman', rarity: 'normal', color: YIZHOU,
    command: 52, strategy: 38, politics: 35, martial: 65, achievement: 30, charisma: 42,
    hp: 840, atk: 62, def: 55, speed: 48, morale: 65, range: 50, vision: 78,
    personality: { aggressiveness: 55, caution: 48, discipline: 58, greed: 40, loyalty: 65 },
    skills: ['fortify'] }),
  g({ id: 'yz_gaopei', name: '高沛', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 50, strategy: 35, politics: 30, martial: 62, achievement: 28, charisma: 38,
    hp: 820, atk: 60, def: 52, speed: 48, morale: 62, range: 50, vision: 75,
    personality: { aggressiveness: 58, caution: 42, discipline: 52, greed: 38, loyalty: 62 },
    skills: ['charge'] }),
  g({ id: 'yz_liuba', name: '刘巴', faction: 'yizhou', troopType: 'archer', rarity: 'elite', color: YIZHOU,
    command: 52, strategy: 78, politics: 82, martial: 22, achievement: 45, charisma: 55,
    hp: 550, atk: 32, def: 35, speed: 42, morale: 72, range: 130, vision: 105,
    personality: { aggressiveness: 15, caution: 85, discipline: 78, greed: 20, loyalty: 72 },
    skills: ['stratagem', 'heal'] }),
  g({ id: 'yz_wulan', name: '吴兰', faction: 'yizhou', troopType: 'cavalry', rarity: 'normal', color: YIZHOU,
    command: 48, strategy: 35, politics: 28, martial: 65, achievement: 28, charisma: 38,
    hp: 830, atk: 62, def: 48, speed: 58, morale: 60, range: 50, vision: 76,
    personality: { aggressiveness: 62, caution: 35, discipline: 48, greed: 40, loyalty: 60 },
    skills: ['charge'] }),
  g({ id: 'yz_pongxi', name: '庞羲', faction: 'yizhou', troopType: 'shield', rarity: 'normal', color: YIZHOU,
    command: 55, strategy: 42, politics: 50, martial: 55, achievement: 32, charisma: 45,
    hp: 850, atk: 52, def: 60, speed: 42, morale: 65, range: 50, vision: 80,
    personality: { aggressiveness: 38, caution: 62, discipline: 58, greed: 45, loyalty: 48 },
    skills: ['shield_wall'] }),
  g({ id: 'yz_liangyi', name: '秦宓', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 38, strategy: 72, politics: 75, martial: 18, achievement: 32, charisma: 65,
    hp: 500, atk: 25, def: 30, speed: 38, morale: 72, range: 50, vision: 95,
    personality: { aggressiveness: 10, caution: 88, discipline: 78, greed: 8, loyalty: 80 },
    skills: ['heal'] }),
  g({ id: 'yz_zhangyi', name: '张翼', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 62, strategy: 52, politics: 48, martial: 65, achievement: 42, charisma: 50,
    hp: 850, atk: 62, def: 58, speed: 48, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 48, caution: 55, discipline: 72, greed: 20, loyalty: 82 },
    skills: ['fortify'] }),
  g({ id: 'yz_liyan', name: '李严', faction: 'yizhou', troopType: 'shield', rarity: 'elite', color: YIZHOU,
    command: 72, strategy: 68, politics: 72, martial: 68, achievement: 55, charisma: 52,
    hp: 900, atk: 62, def: 68, speed: 45, morale: 72, range: 50, vision: 90,
    personality: { aggressiveness: 45, caution: 58, discipline: 65, greed: 65, loyalty: 50 },
    skills: ['fortify', 'shield_wall'] }),
  g({ id: 'yz_wanglian', name: '王连', faction: 'yizhou', troopType: 'infantry', rarity: 'normal', color: YIZHOU,
    command: 42, strategy: 58, politics: 72, martial: 20, achievement: 32, charisma: 55,
    hp: 540, atk: 25, def: 35, speed: 40, morale: 68, range: 50, vision: 90,
    personality: { aggressiveness: 12, caution: 82, discipline: 78, greed: 15, loyalty: 78 },
    skills: ['heal'] }),
  g({ id: 'yz_deng', name: '邓芝', faction: 'yizhou', troopType: 'archer', rarity: 'normal', color: YIZHOU,
    command: 62, strategy: 68, politics: 72, martial: 48, achievement: 48, charisma: 62,
    hp: 720, atk: 48, def: 45, speed: 45, morale: 75, range: 140, vision: 98,
    personality: { aggressiveness: 35, caution: 62, discipline: 75, greed: 12, loyalty: 88 },
    skills: ['stratagem', 'snipe'] }),
  g({ id: 'yz_lengjin', name: '冷苞', faction: 'yizhou', troopType: 'cavalry', rarity: 'normal', color: YIZHOU,
    command: 50, strategy: 38, politics: 28, martial: 68, achievement: 28, charisma: 38,
    hp: 840, atk: 65, def: 48, speed: 58, morale: 62, range: 50, vision: 75,
    personality: { aggressiveness: 65, caution: 32, discipline: 48, greed: 42, loyalty: 58 },
    skills: ['charge'] }),
]

// =================================================================== — 司马家族
// ===================================================================
export const JIN_GENERALS: General[] = [
  g({ id: 'j_simayan', name: '司马炎', faction: 'jin', troopType: 'cavalry', rarity: 'elite', color: JIN,
    command: 78, strategy: 72, politics: 82, martial: 55, achievement: 85, charisma: 70,
    hp: 820, atk: 58, def: 60, speed: 52, morale: 82, range: 50, vision: 100,
    personality: { aggressiveness: 50, caution: 60, discipline: 75, greed: 55, loyalty: 70 },
    skills: ['inspire', 'rally'] }),
  g({ id: 'j_simazhao', name: '司马昭', faction: 'jin', troopType: 'infantry', rarity: 'elite', color: JIN,
    command: 82, strategy: 85, politics: 82, martial: 55, achievement: 80, charisma: 55,
    hp: 780, atk: 55, def: 58, speed: 48, morale: 78, range: 50, vision: 110,
    personality: { aggressiveness: 55, caution: 70, discipline: 80, greed: 85, loyalty: 50 },
    skills: ['stratagem', 'ambush'] }),
  g({ id: 'j_simashi', name: '司马师', faction: 'jin', troopType: 'infantry', rarity: 'elite', color: JIN,
    command: 80, strategy: 78, politics: 80, martial: 58, achievement: 72, charisma: 60,
    hp: 800, atk: 58, def: 60, speed: 48, morale: 80, range: 50, vision: 105,
    personality: { aggressiveness: 45, caution: 72, discipline: 85, greed: 70, loyalty: 55 },
    skills: ['fortify', 'stratagem'] }),
  g({ id: 'j_dengai2', name: '邓艾', faction: 'jin', troopType: 'infantry', rarity: 'legend', color: JIN,
    command: 88, strategy: 85, politics: 60, martial: 78, achievement: 80, charisma: 55,
    hp: 880, atk: 72, def: 65, speed: 55, morale: 82, range: 50, vision: 110,
    personality: { aggressiveness: 70, caution: 55, discipline: 85, greed: 65, loyalty: 75 },
    skills: ['ambush', 'stratagem'] }),
  g({ id: 'j_zhonghui2', name: '钟会', faction: 'jin', troopType: 'cavalry', rarity: 'elite', color: JIN,
    command: 82, strategy: 88, politics: 75, martial: 55, achievement: 72, charisma: 48,
    hp: 750, atk: 55, def: 55, speed: 55, morale: 70, range: 50, vision: 115,
    personality: { aggressiveness: 60, caution: 55, discipline: 65, greed: 85, loyalty: 25 },
    skills: ['stratagem', 'fire_attack'] }),
  g({ id: 'j_duyu', name: '杜预', faction: 'jin', troopType: 'archer', rarity: 'elite', color: JIN,
    command: 85, strategy: 88, politics: 82, martial: 50, achievement: 78, charisma: 72,
    hp: 720, atk: 52, def: 50, speed: 48, morale: 82, range: 150, vision: 120,
    personality: { aggressiveness: 45, caution: 68, discipline: 88, greed: 20, loyalty: 85 },
    skills: ['stratagem', 'snipe'] }),
  g({ id: 'j_wangjun', name: '王濬', faction: 'jin', troopType: 'infantry', rarity: 'elite', color: JIN,
    command: 78, strategy: 72, politics: 65, martial: 72, achievement: 72, charisma: 65,
    hp: 880, atk: 68, def: 62, speed: 52, morale: 80, range: 50, vision: 95,
    personality: { aggressiveness: 62, caution: 50, discipline: 78, greed: 35, loyalty: 80 },
    skills: ['charge', 'fortify'] }),
  g({ id: 'j_yanghu', name: '羊祜', faction: 'jin', troopType: 'shield', rarity: 'elite', color: JIN,
    command: 82, strategy: 80, politics: 88, martial: 48, achievement: 75, charisma: 90,
    hp: 750, atk: 45, def: 65, speed: 42, morale: 88, range: 50, vision: 105,
    personality: { aggressiveness: 25, caution: 80, discipline: 92, greed: 8, loyalty: 92 },
    skills: ['rally', 'heal'] }),
  g({ id: 'j_jiachong', name: '贾充', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 55, strategy: 68, politics: 72, martial: 35, achievement: 55, charisma: 30,
    hp: 650, atk: 40, def: 45, speed: 42, morale: 65, range: 50, vision: 90,
    personality: { aggressiveness: 40, caution: 72, discipline: 60, greed: 85, loyalty: 35 },
    skills: ['stratagem'] }),
  g({ id: 'j_wenjyang', name: '文鸯', faction: 'jin', troopType: 'cavalry', rarity: 'elite', color: JIN,
    command: 65, strategy: 48, politics: 30, martial: 92, achievement: 55, charisma: 60,
    hp: 1000, atk: 88, def: 58, speed: 72, morale: 78, range: 50, vision: 82,
    personality: { aggressiveness: 88, caution: 15, discipline: 62, greed: 30, loyalty: 65 },
    skills: ['charge', 'duel'] }),
  // 补充
  g({ id: 'j_zhugexu', name: '诸葛绪', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 58, strategy: 52, politics: 48, martial: 55, achievement: 40, charisma: 42,
    hp: 780, atk: 52, def: 55, speed: 45, morale: 65, range: 50, vision: 85,
    personality: { aggressiveness: 40, caution: 62, discipline: 65, greed: 45, loyalty: 55 },
    skills: ['fortify'] }),
  g({ id: 'j_wangyuan', name: '王元姬', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 38, strategy: 62, politics: 72, martial: 18, achievement: 35, charisma: 75,
    hp: 480, atk: 22, def: 32, speed: 40, morale: 78, range: 50, vision: 95,
    personality: { aggressiveness: 8, caution: 92, discipline: 88, greed: 5, loyalty: 95 },
    skills: ['heal', 'rally'] }),
  g({ id: 'j_huzhao', name: '胡昭', faction: 'jin', troopType: 'archer', rarity: 'normal', color: JIN,
    command: 45, strategy: 72, politics: 68, martial: 25, achievement: 35, charisma: 62,
    hp: 580, atk: 35, def: 38, speed: 42, morale: 72, range: 140, vision: 100,
    personality: { aggressiveness: 15, caution: 82, discipline: 78, greed: 8, loyalty: 85 },
    skills: ['stratagem'] }),
  g({ id: 'j_zhongyu', name: '钟毓', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 55, strategy: 62, politics: 65, martial: 42, achievement: 38, charisma: 50,
    hp: 720, atk: 45, def: 50, speed: 45, morale: 68, range: 50, vision: 88,
    personality: { aggressiveness: 35, caution: 65, discipline: 72, greed: 40, loyalty: 58 },
    skills: ['stratagem'] }),
  g({ id: 'j_malong', name: '马隆', faction: 'jin', troopType: 'spearman', rarity: 'elite', color: JIN,
    command: 75, strategy: 68, politics: 55, martial: 78, achievement: 58, charisma: 62,
    hp: 920, atk: 72, def: 68, speed: 52, morale: 80, range: 50, vision: 90,
    personality: { aggressiveness: 58, caution: 50, discipline: 82, greed: 22, loyalty: 82 },
    skills: ['fortify', 'charge'] }),
  g({ id: 'j_tangbin', name: '唐彬', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 62, strategy: 55, politics: 52, martial: 62, achievement: 42, charisma: 50,
    hp: 830, atk: 58, def: 58, speed: 48, morale: 72, range: 50, vision: 82,
    personality: { aggressiveness: 48, caution: 55, discipline: 72, greed: 25, loyalty: 75 },
    skills: ['fortify'] }),
  g({ id: 'j_huwei', name: '胡奋', faction: 'jin', troopType: 'cavalry', rarity: 'normal', color: JIN,
    command: 60, strategy: 50, politics: 48, martial: 68, achievement: 42, charisma: 48,
    hp: 860, atk: 65, def: 52, speed: 58, morale: 70, range: 50, vision: 80,
    personality: { aggressiveness: 58, caution: 42, discipline: 65, greed: 30, loyalty: 72 },
    skills: ['charge'] }),
  g({ id: 'j_zhanghua', name: '张华', faction: 'jin', troopType: 'archer', rarity: 'elite', color: JIN,
    command: 58, strategy: 78, politics: 82, martial: 25, achievement: 55, charisma: 68,
    hp: 580, atk: 35, def: 38, speed: 42, morale: 75, range: 140, vision: 108,
    personality: { aggressiveness: 18, caution: 78, discipline: 82, greed: 15, loyalty: 80 },
    skills: ['stratagem', 'heal'] }),
  g({ id: 'j_wangrong', name: '王戎', faction: 'jin', troopType: 'infantry', rarity: 'normal', color: JIN,
    command: 55, strategy: 65, politics: 62, martial: 42, achievement: 45, charisma: 48,
    hp: 700, atk: 45, def: 48, speed: 45, morale: 65, range: 50, vision: 88,
    personality: { aggressiveness: 30, caution: 68, discipline: 58, greed: 70, loyalty: 50 },
    skills: ['stratagem'] }),
  g({ id: 'j_simaliang', name: '司马亮', faction: 'jin', troopType: 'cavalry', rarity: 'normal', color: JIN,
    command: 55, strategy: 52, politics: 58, martial: 50, achievement: 42, charisma: 48,
    hp: 760, atk: 50, def: 50, speed: 52, morale: 62, range: 50, vision: 82,
    personality: { aggressiveness: 38, caution: 62, discipline: 55, greed: 52, loyalty: 55 },
    skills: ['inspire'] }),
]

export const NEW_FACTIONS = {
  DONG_GENERALS,
  YUAN_GENERALS,
  XILIANG_GENERALS,
  JINGZHOU_GENERALS,
  YIZHOU_GENERALS,
  JIN_GENERALS,
}

export const ALL_NEW_GENERALS: General[] = [
  ...DONG_GENERALS,
  ...YUAN_GENERALS,
  ...XILIANG_GENERALS,
  ...JINGZHOU_GENERALS,
  ...YIZHOU_GENERALS,
  ...JIN_GENERALS,
]
