import { Skill } from '../types'

// ===== Skill Definitions =====
// Each skill is a template. Generals reference these by id.

export const SKILLS: Record<string, Skill> = {
  charge: {
    id: 'charge',
    name: '冲锋',
    description: '短时间提升移速和首次近战伤害',
    cooldown: 80,
    triggerChance: 0.6,
    targetType: 'self',
    range: 0,
    effects: [
      { type: 'buff_speed', value: 50, duration: 20 },
      { type: 'buff_atk', value: 30, duration: 10 },
    ],
  },
  inspire: {
    id: 'inspire',
    name: '激励',
    description: '提高周围友军士气和攻击力',
    cooldown: 80,
    triggerChance: 0.55,
    targetType: 'ally',
    range: 150,
    effects: [
      { type: 'buff_morale', value: 25, duration: 50 },
      { type: 'buff_atk', value: 12, duration: 40 },
    ],
  },
  stratagem: {
    id: 'stratagem',
    name: '谋断',
    description: '短时间提升命中和攻击',
    cooldown: 90,
    triggerChance: 0.55,
    targetType: 'self',
    range: 0,
    effects: [{ type: 'buff_atk', value: 25, duration: 30 }],
  },
  fortify: {
    id: 'fortify',
    name: '坚守',
    description: '短时间提升防御和抗溃败',
    cooldown: 80,
    triggerChance: 0.5,
    targetType: 'self',
    range: 0,
    effects: [
      { type: 'buff_def', value: 35, duration: 30 },
      { type: 'buff_morale', value: 15, duration: 30 },
    ],
  },
  ambush: {
    id: 'ambush',
    name: '奇袭',
    description: '突袭敌人造成额外伤害并降低士气',
    cooldown: 100,
    triggerChance: 0.45,
    targetType: 'enemy',
    range: 80,
    effects: [
      { type: 'damage', value: 40, duration: 0 },
      { type: 'debuff_morale', value: 15, duration: 0 },
    ],
  },
  fire_attack: {
    id: 'fire_attack',
    name: '火计',
    description: '范围火攻，伤害敌人并点燃森林',
    cooldown: 80,
    triggerChance: 0.55,
    targetType: 'area',
    range: 120,
    effects: [
      { type: 'damage', value: 15, duration: 20, radius: 80 },
      { type: 'debuff_morale', value: 10, duration: 20, radius: 80 },
    ],
  },
  heal: {
    id: 'heal',
    name: '治疗',
    description: '恢复自身和附近友军生命值（随政治提升）',
    cooldown: 70,
    triggerChance: 0.6,
    targetType: 'ally',
    range: 100,
    effects: [{ type: 'heal', value: 25, duration: 0 }],
  },
  roar: {
    id: 'roar',
    name: '虎啸',
    description: '震慑周围敌人降低士气',
    cooldown: 90,
    triggerChance: 0.5,
    targetType: 'enemy',
    range: 100,
    effects: [{ type: 'debuff_morale', value: 20, duration: 0 }],
  },
  rally: {
    id: 'rally',
    name: '整军',
    description: '大幅恢复士气并提高防御',
    cooldown: 100,
    triggerChance: 0.5,
    targetType: 'ally',
    range: 130,
    effects: [
      { type: 'buff_morale', value: 35, duration: 60 },
      { type: 'buff_def', value: 15, duration: 40 },
    ],
  },
  snipe: {
    id: 'snipe',
    name: '精射',
    description: '精确射击造成高额伤害',
    cooldown: 70,
    triggerChance: 0.55,
    targetType: 'enemy',
    range: 200,
    effects: [{ type: 'damage', value: 50, duration: 0 }],
  },
  shield_wall: {
    id: 'shield_wall',
    name: '盾墙',
    description: '大幅提升防御',
    cooldown: 90,
    triggerChance: 0.5,
    targetType: 'self',
    range: 0,
    effects: [{ type: 'buff_def', value: 50, duration: 25 }],
  },
  duel: {
    id: 'duel',
    name: '单挑',
    description: '对单个目标造成基于武勇的高额伤害',
    cooldown: 100,
    triggerChance: 0.5,
    targetType: 'enemy',
    range: 60,
    effects: [{ type: 'damage', value: 60, duration: 0 }],
  },
}
