import { Skill } from '../types'

export const SKILLS: Record<string, Skill> = {
  charge: {
    id: 'charge',
    name: '冲锋',
    description: '短时间提升移速和攻击力，适合骑兵突击',
    cooldown: 80,
    triggerChance: 0.6,
    targetType: 'self',
    range: 0,
    effects: [
      { type: 'buff_speed', value: 45, duration: 20 },
      { type: 'buff_atk', value: 25, duration: 12 },
    ],
  },
  inspire: {
    id: 'inspire',
    name: '激励',
    description: '提高友军士气和攻击力，进攻前鼓舞',
    cooldown: 80,
    triggerChance: 0.55,
    targetType: 'ally',
    range: 150,
    effects: [
      { type: 'buff_morale', value: 22, duration: 50 },
      { type: 'buff_atk', value: 10, duration: 40 },
    ],
  },
  stratagem: {
    id: 'stratagem',
    name: '谋断',
    description: '提升攻击并降低周围敌人防御',
    cooldown: 85,
    triggerChance: 0.55,
    targetType: 'self',
    range: 0,
    effects: [
      { type: 'buff_atk', value: 22, duration: 35 },
      { type: 'buff_speed', value: 10, duration: 35 },
    ],
  },
  fortify: {
    id: 'fortify',
    name: '坚守',
    description: '提升防御和士气，适合步兵/枪兵扛线',
    cooldown: 75,
    triggerChance: 0.5,
    targetType: 'self',
    range: 0,
    effects: [
      { type: 'buff_def', value: 30, duration: 35 },
      { type: 'buff_morale', value: 12, duration: 35 },
    ],
  },
  ambush: {
    id: 'ambush',
    name: '奇袭',
    description: '突袭敌人造成伤害并大幅打击士气',
    cooldown: 75,
    triggerChance: 0.5,
    targetType: 'enemy',
    range: 80,
    effects: [
      { type: 'damage', value: 45, duration: 0 },
      { type: 'debuff_morale', value: 18, duration: 0 },
    ],
  },
  fire_attack: {
    id: 'fire_attack',
    name: '火计',
    description: '范围火攻，伤害敌人并点燃周围森林',
    cooldown: 90,
    triggerChance: 0.5,
    targetType: 'area',
    range: 120,
    effects: [
      { type: 'damage', value: 18, duration: 20, radius: 80 },
      { type: 'debuff_morale', value: 12, duration: 20, radius: 80 },
    ],
  },
  heal: {
    id: 'heal',
    name: '治疗',
    description: '恢复友军生命值，效果随政治和魅力提升',
    cooldown: 70,
    triggerChance: 0.6,
    targetType: 'ally',
    range: 110,
    effects: [{ type: 'heal', value: 28, duration: 0 }],
  },
  roar: {
    id: 'roar',
    name: '虎啸',
    description: '震慑周围敌人，大幅降低士气',
    cooldown: 85,
    triggerChance: 0.5,
    targetType: 'enemy',
    range: 100,
    effects: [{ type: 'debuff_morale', value: 18, duration: 0 }],
  },
  rally: {
    id: 'rally',
    name: '整军',
    description: '大幅恢复士气并提高全军防御，翻盘核心',
    cooldown: 95,
    triggerChance: 0.5,
    targetType: 'ally',
    range: 140,
    effects: [
      { type: 'buff_morale', value: 30, duration: 60 },
      { type: 'buff_def', value: 12, duration: 45 },
    ],
  },
  snipe: {
    id: 'snipe',
    name: '精射',
    description: '精确射击造成高额伤害，弓兵核心输出',
    cooldown: 80,
    triggerChance: 0.5,
    targetType: 'enemy',
    range: 200,
    effects: [{ type: 'damage', value: 45, duration: 0 }],
  },
  shield_wall: {
    id: 'shield_wall',
    name: '盾墙',
    description: '超高防御并为附近友军提供掩护',
    cooldown: 85,
    triggerChance: 0.5,
    targetType: 'self',
    range: 0,
    effects: [
      { type: 'buff_def', value: 45, duration: 30 },
      { type: 'buff_morale', value: 8, duration: 30 },
    ],
  },
  duel: {
    id: 'duel',
    name: '单挑',
    description: '对目标造成武勇加成的高额伤害，并回复自身士气',
    cooldown: 90,
    triggerChance: 0.5,
    targetType: 'enemy',
    range: 60,
    effects: [
      { type: 'damage', value: 55, duration: 0 },
      { type: 'buff_morale', value: 10, duration: 0 },
    ],
  },
}
